#!/bin/bash
# Nim bindings for the civetweb C API subset we use. c2nim cannot parse the whole civetweb.h (attribute macros), so the needed
# declarations (functions, structs, callback typedef) are extracted verbatim from the real header and then translated by c2nim.
# Usage: tools/http/gen.sh /path/to/prefix/include
set -e
INC="${1:?include dir}"; OUT="$(dirname "$0")/../../src/common/civetc"; mkdir -p "$OUT"
tmp=$(mktemp --suffix=.h)
python3 - "$INC/civetweb.h" "$tmp" <<'PY'
import re, sys
src = open(sys.argv[1]).read()
funcs = ["mg_init_library", "mg_exit_library", "mg_start", "mg_stop", "mg_set_request_handler", "mg_get_request_info", "mg_get_user_data",
         "mg_get_context", "mg_write", "mg_printf", "mg_read", "mg_send_http_error", "mg_send_http_ok", "mg_response_header_start",
         "mg_response_header_add", "mg_response_header_send", "mg_get_header", "mg_send_chunk", "mg_lock_connection", "mg_unlock_connection"]
out = ['#ifdef C2NIM', '#cdecl', '#def CIVETWEB_API', '#def PRINTF_ARGS(a,b)', '#def PRINTF_FORMAT_STRING(s) s',
       '#@', 'type', '  uint8_t* = uint8', '  uint16_t* = uint16', '  uint32_t* = uint32', '  uint64_t* = uint64', '  int64_t* = int64', '  time_t* = int64',
       '  mg_context* {.importc: "struct mg_context", header: civetHeader, incompleteStruct.} = object',
       '  mg_connection* {.importc: "struct mg_connection", header: civetHeader, incompleteStruct.} = object',
       '  mg_client_cert* {.importc: "struct mg_client_cert", header: civetHeader, incompleteStruct.} = object', '@#', '#endif']
out.append(re.search(r"#define MG_MAX_HEADERS[^\n]*", src).group(0))
for s in ["mg_header", "mg_request_info", "mg_callbacks"]:
    m = re.search(r"\nstruct %s \{.*?\n\};" % s, src, re.S)
    body = m.group(0).strip()
    body = re.sub(r"#if defined\(MG_EXPERIMENTAL_INTERFACES\).*?#endif", "", body, flags=re.S)   # experimental members are not built
    out.append(body)
out.append(re.search(r"typedef int \(\*mg_request_handler\)\(.*?\);", src, re.S).group(0))
for f in funcs:
    m = re.search(r"CIVETWEB_API[^;{]*?\b%s\s*\(.*?\);" % f, src, re.S)
    if not m: sys.exit("declaration not found: " + f)
    out.append(re.sub(r"__attribute__\(\(.*?\)\)", "", m.group(0)))
open(sys.argv[2], "w").write("\n".join(out) + "\n")
PY
c2nim --cdecl --skipcomments --header:civetHeader -o:"$OUT/civetweb.nim" "$tmp" 2>&1 | grep -E 'Error' | head -5 || true
# civetweb structs have no typedef: the C name is `struct mg_xxx`
sed -i -E 's/importc: "(mg_header|mg_request_info|mg_callbacks)"/importc: "struct \1"/' "$OUT/civetweb.nim"
sed -i '1i # Generated by tools/http/gen.sh (c2nim) from civetweb.h. Do not edit.\nconst civetHeader = "civetweb.h"' "$OUT/civetweb.nim"
rm -f "$tmp"
