# Generated by tools/k8s/gen.sh (c2nim) from kubernetes/include/apiClient.h. Do not edit.
const k8sHeader = "kubernetes/include/apiClient.h"
import list, keyvalue
type
  CURL* {.importc: "CURL", header: "curl/curl.h", incompleteStruct.} = object
  curl_off_t* = int64
type
  sslConfig_t* {.importc: "sslConfig_t", header: k8sHeader, bycopy.} = object
    clientCertFile* {.importc: "clientCertFile".}: cstring
    clientKeyFile* {.importc: "clientKeyFile".}: cstring
    CACertFile* {.importc: "CACertFile".}: cstring
    insecureSkipTlsVerify* {.importc: "insecureSkipTlsVerify".}: cint

  curlConfig_t* {.importc: "curlConfig_t", header: k8sHeader, bycopy.} = object
    verbose* {.importc: "verbose".}: clong
    keepalive* {.importc: "keepalive".}: cint
    keepidle* {.importc: "keepidle".}: clong
    keepintvl* {.importc: "keepintvl".}: clong

  apiClient_t* {.importc: "apiClient_t", header: k8sHeader, bycopy.} = object
    basePath* {.importc: "basePath".}: cstring
    sslConfig* {.importc: "sslConfig".}: ptr sslConfig_t
    curlConfig* {.importc: "curlConfig".}: ptr curlConfig_t
    curl_pre_invoke_func* {.importc: "curl_pre_invoke_func".}: proc (a1: ptr CURL) {.
        cdecl.}
    dataReceived* {.importc: "dataReceived".}: pointer
    dataReceivedLen* {.importc: "dataReceivedLen".}: clong
    data_callback_func* {.importc: "data_callback_func".}: proc (a1: ptr pointer;
        a2: ptr clong) {.cdecl.}
    progress_func* {.importc: "progress_func".}: proc (a1: pointer; a2: curl_off_t;
        a3: curl_off_t; a4: curl_off_t; a5: curl_off_t): cint {.cdecl.}
    progress_data* {.importc: "progress_data".}: pointer
    response_code* {.importc: "response_code".}: clong
    apiKeys_BearerToken* {.importc: "apiKeys_BearerToken".}: ptr list_t


proc apiClient_create*(): ptr apiClient_t {.cdecl, importc: "apiClient_create",
                                        header: k8sHeader.}
proc apiClient_create_with_base_path*(basePath: cstring;
                                     sslConfig: ptr sslConfig_t;
                                     apiKeys_BearerToken: ptr list_t): ptr apiClient_t {.
    cdecl, importc: "apiClient_create_with_base_path", header: k8sHeader.}
proc apiClient_free*(apiClient: ptr apiClient_t) {.cdecl, importc: "apiClient_free",
    header: k8sHeader.}
proc apiClient_invoke*(apiClient: ptr apiClient_t; operationParameter: cstring;
                      queryParameters: ptr list_t; headerParameters: ptr list_t;
                      formParameters: ptr list_t; headerType: ptr list_t;
                      contentType: ptr list_t; bodyParameters: cstring;
                      bodyParametersLength: csize_t; requestType: cstring) {.cdecl,
    importc: "apiClient_invoke", header: k8sHeader.}
proc sslConfig_create*(clientCertFile: cstring; clientKeyFile: cstring;
                      CACertFile: cstring; insecureSkipTlsVerify: cint): ptr sslConfig_t {.
    cdecl, importc: "sslConfig_create", header: k8sHeader.}
proc sslConfig_free*(sslConfig: ptr sslConfig_t) {.cdecl, importc: "sslConfig_free",
    header: k8sHeader.}
proc strReplace*(orig: cstring; rep: cstring; with: cstring): cstring {.cdecl,
    importc: "strReplace", header: k8sHeader.}

proc apiClient_setupGlobalEnv*() {.cdecl, importc: "apiClient_setupGlobalEnv",
                                 header: k8sHeader.}

proc apiClient_unsetupGlobalEnv*() {.cdecl, importc: "apiClient_unsetupGlobalEnv",
                                   header: k8sHeader.}