# Generated by tools/k8s/gen.sh (c2nim) from kubernetes/include/generic.h. Do not edit.
const k8sHeader = "kubernetes/include/generic.h"
import list, apiclient
type
  genericClient_t* {.importc: "genericClient_t", header: k8sHeader, bycopy.} = object
    client* {.importc: "client".}: ptr apiClient_t
    apiGroup* {.importc: "apiGroup".}: cstring
    apiVersion* {.importc: "apiVersion".}: cstring
    resourcePlural* {.importc: "resourcePlural".}: cstring


proc genericClient_create*(client: ptr apiClient_t; apiGroup: cstring;
                          apiVersion: cstring; resourcePlural: cstring): ptr genericClient_t {.
    cdecl, importc: "genericClient_create", header: k8sHeader.}
proc genericClient_free*(client: ptr genericClient_t) {.cdecl,
    importc: "genericClient_free", header: k8sHeader.}
proc Generic_readNamespacedResource*(client: ptr genericClient_t; ns: cstring;
                                    name: cstring): cstring {.cdecl,
    importc: "Generic_readNamespacedResource", header: k8sHeader.}
proc Generic_readResource*(client: ptr genericClient_t; name: cstring): cstring {.
    cdecl, importc: "Generic_readResource", header: k8sHeader.}
proc Generic_listNamespaced*(client: ptr genericClient_t; ns: cstring;
                            queryParameters: ptr list_t): cstring {.cdecl,
    importc: "Generic_listNamespaced", header: k8sHeader.}
proc Generic_list*(client: ptr genericClient_t; queryParameters: ptr list_t): cstring {.
    cdecl, importc: "Generic_list", header: k8sHeader.}
proc Generic_deleteNamespacedResource*(client: ptr genericClient_t; ns: cstring;
                                      name: cstring; body: cstring): cstring {.cdecl,
    importc: "Generic_deleteNamespacedResource", header: k8sHeader.}
proc Generic_deleteResource*(client: ptr genericClient_t; name: cstring; body: cstring): cstring {.
    cdecl, importc: "Generic_deleteResource", header: k8sHeader.}
proc Generic_createNamespacedResource*(client: ptr genericClient_t; ns: cstring;
                                      body: cstring; queryParameters: ptr list_t): cstring {.
    cdecl, importc: "Generic_createNamespacedResource", header: k8sHeader.}
proc Generic_createResource*(client: ptr genericClient_t; body: cstring;
                            queryParameters: ptr list_t): cstring {.cdecl,
    importc: "Generic_createResource", header: k8sHeader.}
proc Generic_replaceNamespacedResource*(client: ptr genericClient_t; ns: cstring;
                                       name: cstring; body: cstring): cstring {.
    cdecl, importc: "Generic_replaceNamespacedResource", header: k8sHeader.}
proc Generic_replaceResource*(client: ptr genericClient_t; name: cstring;
                             body: cstring): cstring {.cdecl,
    importc: "Generic_replaceResource", header: k8sHeader.}
proc Generic_patchNamespacedResource*(client: ptr genericClient_t; ns: cstring;
                                     name: cstring; body: cstring;
                                     queryParameters: ptr list_t;
                                     headerParameters: ptr list_t;
                                     formParameters: ptr list_t;
                                     headerType: ptr list_t;
                                     contentType: ptr list_t): cstring {.cdecl,
    importc: "Generic_patchNamespacedResource", header: k8sHeader.}
proc Generic_patchResource*(client: ptr genericClient_t; name: cstring; body: cstring;
                           queryParameters: ptr list_t;
                           headerParameters: ptr list_t;
                           formParameters: ptr list_t; headerType: ptr list_t;
                           contentType: ptr list_t): cstring {.cdecl,
    importc: "Generic_patchResource", header: k8sHeader.}