# Generated by tools/k8s/gen.sh (c2nim) from kubernetes/config/incluster_config.h. Do not edit.
const k8sHeader = "kubernetes/config/incluster_config.h"
import list, apiclient

proc load_incluster_config*(pBasePath: cstringArray;
                           pSslConfig: ptr ptr sslConfig_t; pApiKeys: ptr ptr list_t): cint {.
    cdecl, importc: "load_incluster_config", header: k8sHeader.}