# Generated by tools/k8s/gen.sh (c2nim) from kubernetes/include/keyValuePair.h. Do not edit.
const k8sHeader = "kubernetes/include/keyValuePair.h"
import list
type
  keyValuePair_t* {.importc: "keyValuePair_t", header: k8sHeader, bycopy.} = object
    key* {.importc: "key".}: cstring
    value* {.importc: "value".}: pointer


proc keyValuePair_create*(key: cstring; value: pointer): ptr keyValuePair_t {.cdecl,
    importc: "keyValuePair_create", header: k8sHeader.}
proc keyValuePair_create_allocate*(key: cstring; value: cdouble): ptr keyValuePair_t {.
    cdecl, importc: "keyValuePair_create_allocate", header: k8sHeader.}
proc keyValuePair_free*(keyValuePair: ptr keyValuePair_t) {.cdecl,
    importc: "keyValuePair_free", header: k8sHeader.}