# Generated by tools/k8s/gen.sh (c2nim) from kubernetes/config/kube_config.h. Do not edit.
const k8sHeader = "kubernetes/config/kube_config.h"
import list, apiclient

proc load_kube_config*(pBasePath: cstringArray; pSslConfig: ptr ptr sslConfig_t;
                      pApiKeys: ptr ptr list_t; configFileName: cstring): cint {.cdecl,
    importc: "load_kube_config", header: k8sHeader.}

proc load_kube_config_buffer*(pBasePath: cstringArray;
                             pSslConfig: ptr ptr sslConfig_t;
                             pApiKeys: ptr ptr list_t; buffer: cstring): cint {.cdecl,
    importc: "load_kube_config_buffer", header: k8sHeader.}

proc free_client_config*(basePath: cstring; sslConfig: ptr sslConfig_t;
                        apiKeys: ptr list_t) {.cdecl, importc: "free_client_config",
    header: k8sHeader.}