# Generated by tools/k8s/gen.sh (c2nim) from kubernetes/include/list.h. Do not edit.
const k8sHeader = "kubernetes/include/list.h"
type
  listEntry_t* {.importc: "listEntry_t", header: k8sHeader, bycopy.} = object
    nextListEntry* {.importc: "nextListEntry".}: ptr listEntry_t
    prevListEntry* {.importc: "prevListEntry".}: ptr listEntry_t
    data* {.importc: "data".}: pointer

  list_t* {.importc: "list_t", header: k8sHeader, bycopy.} = object
    firstEntry* {.importc: "firstEntry".}: ptr listEntry_t
    lastEntry* {.importc: "lastEntry".}: ptr listEntry_t
    count* {.importc: "count".}: clong


proc list_createList*(): ptr list_t {.cdecl, importc: "list_createList",
                                  header: k8sHeader.}
proc list_freeList*(listToFree: ptr list_t) {.cdecl, importc: "list_freeList",
    header: k8sHeader.}
proc list_addElement*(list: ptr list_t; dataToAddInList: pointer) {.cdecl,
    importc: "list_addElement", header: k8sHeader.}
proc list_getElementAt*(list: ptr list_t; indexOfElement: clong): ptr listEntry_t {.
    cdecl, importc: "list_getElementAt", header: k8sHeader.}
proc list_getWithIndex*(list: ptr list_t; index: cint): ptr listEntry_t {.cdecl,
    importc: "list_getWithIndex", header: k8sHeader.}
proc list_removeElement*(list: ptr list_t; elementToRemove: ptr listEntry_t) {.cdecl,
    importc: "list_removeElement", header: k8sHeader.}
proc list_iterateThroughListForward*(list: ptr list_t; operationToPerform: proc (
    a1: ptr listEntry_t; a2: pointer) {.cdecl.};
    additionalDataNeededForCallbackFunction: pointer) {.cdecl,
    importc: "list_iterateThroughListForward", header: k8sHeader.}
proc list_iterateThroughListBackward*(list: ptr list_t; operationToPerform: proc (
    a1: ptr listEntry_t; a2: pointer) {.cdecl.};
    additionalDataNeededForCallbackFunction: pointer) {.cdecl,
    importc: "list_iterateThroughListBackward", header: k8sHeader.}
proc listEntry_printAsInt*(listEntry: ptr listEntry_t; additionalData: pointer) {.
    cdecl, importc: "listEntry_printAsInt", header: k8sHeader.}
proc listEntry_free*(listEntry: ptr listEntry_t; additionalData: pointer) {.cdecl,
    importc: "listEntry_free", header: k8sHeader.}
proc findStrInStrList*(strList: ptr list_t; str: cstring): cstring {.cdecl,
    importc: "findStrInStrList", header: k8sHeader.}
proc clear_and_free_string_list*(list: ptr list_t) {.cdecl,
    importc: "clear_and_free_string_list", header: k8sHeader.}