# Generated by tools/k8s/gen.sh (c2nim) from kubernetes/watch/watch_util.h. Do not edit.
const k8sHeader = "kubernetes/watch/watch_util.h"
type
  KUBE_WATCH_EVENT_HANDLER_FUNC* = proc (a1: cstring) {.cdecl.}

proc kubernets_watch_handler*(pData: ptr pointer; pDataLen: ptr clong;
                             event_hander: KUBE_WATCH_EVENT_HANDLER_FUNC) {.cdecl,
    importc: "kubernets_watch_handler", header: k8sHeader.}