#!/bin/bash
# Generates Nim bindings for NNG from its real headers with the official c2nim tool (no hand-written wrapper).
# Usage: tools/nng/gen.sh /path/to/nng/include   (headers: nng/nng.h and the protocol/TLS headers we use)
set -e
INC="${1:?path to NNG include dir}"; OUT="$(dirname "$0")/../../src/common/nngc"; mkdir -p "$OUT"
gen() { # header outname import_line
  local hdr="$1" out="$2" imp="$3" tmp opaque; tmp=$(mktemp --suffix=.h)
  # forward-declared opaque structs (typedef struct X X;) are dropped by c2nim: declare them as incomplete types
  opaque=$(grep -oE '^typedef[[:space:]]+struct[[:space:]]+[a-z_0-9]+[[:space:]]+[a-z_0-9]+;' "$INC/$hdr" | awk '{gsub(";","",$4); print $4}' | sort -u | while read n; do
    grep -qE "^(typedef )?struct $n \\{|^struct $n \\{" "$INC/$hdr" && continue   # full definition exists
    printf 'type %s* {.importc: \"%s\", header: nngHeader, incompleteStruct.} = object\n' "$n" "$n"; done)
  [ -n "$opaque" ] && imp="$imp"$'\n'"$opaque"
  { printf '#ifdef C2NIM\n#cdecl\n#def NNG_DECL\n#def NNG_DEPRECATED\n#def NNG_STATIC_LIB\n#def NNG_SHARED_LIB\n'
    [ -n "$imp" ] && printf '#@\n%s\n@#\n' "$imp"
    printf '#endif\n'
    sed 's|^#define NNG_MAXADDRSTRLEN.*|#define NNG_MAXADDRSTRLEN 144|' "$INC/$hdr"; } > "$tmp"
  c2nim --cdecl --skipcomments --header:nngHeader -o:"$OUT/$out" "$tmp" 2>&1 | grep -E 'Error' || true
  sed -i '1i # Generated by tools/nng/gen.sh (c2nim) from '"$hdr"'. Do not edit.\nconst nngHeader = "'"$hdr"'"' "$OUT/$out"
  # drop our incomplete declaration when c2nim also produced a full definition of the same type
  for n in $(grep -oE '^type [a-z_0-9]+\*' "$OUT/$out" | awk '{gsub("\\*","",$2); print $2}'); do
    grep -qE "^  $n\\* " "$OUT/$out" && sed -i "/^type $n\\* {.importc.*incompleteStruct/d" "$OUT/$out"
  done
  rm -f "$tmp"
}
gen nng/nng.h core.nim "type
  uint8_t* = uint8
  uint16_t* = uint16
  uint32_t* = uint32
  uint64_t* = uint64
  int32_t* = int32
  int64_t* = int64"
gen nng/supplemental/tls/tls.h tls.nim "import core"
for p in reqrep0/req reqrep0/rep pipeline0/push pipeline0/pull; do gen nng/protocol/$p.h proto_$(basename $p).nim "import core"; done
