#!/bin/bash
# Generates Nim bindings for the official Kubernetes C client (the subset we use) with c2nim.
# Usage: tools/k8s/gen.sh /path/to/prefix/include/kubernetes
set -e
INC="${1:?path to <prefix>/include/kubernetes}"; OUT="$(dirname "$0")/../../src/common/k8sc"; mkdir -p "$OUT"
gen() { # header outname prelude
  local hdr="$1" out="$2" imp="$3" tmp; tmp=$(mktemp --suffix=.h)
  { printf '#ifdef C2NIM\n#cdecl\n'
    [ -n "$imp" ] && printf '#@\n%s\n@#\n' "$imp"
    printf '#endif\n'
    grep -v "^[[:space:]]*#include" "$INC/$hdr"; } > "$tmp"
  c2nim --cdecl --skipcomments --header:k8sHeader -o:"$OUT/$out" "$tmp" 2>&1 | grep -E 'Error' || true
  sed -i '1i # Generated by tools/k8s/gen.sh (c2nim) from kubernetes/'"$hdr"'. Do not edit.\nconst k8sHeader = "kubernetes/'"$hdr"'"' "$OUT/$out"
  rm -f "$tmp"
}
gen include/list.h list.nim ""
gen include/keyValuePair.h keyvalue.nim "import list"
gen include/apiClient.h apiclient.nim "import list, keyvalue
type
  CURL* {.importc: \"CURL\", header: \"curl/curl.h\", incompleteStruct.} = object
  curl_off_t* = int64"
gen include/generic.h generic.nim "import list, apiclient"
gen config/kube_config.h kubeconfig.nim "import list, apiclient"
gen config/incluster_config.h incluster.nim "import list, apiclient"
gen watch/watch_util.h watchutil.nim ""
