## Chosen transport (ADR 0010): NNG through bindings generated by c2nim (tools/nng/gen.sh).
## Build: nim c -r -d:nngPrefix=<NNG install> tests/integration/tnng.nim
import std/[unittest, os, strutils, atomics, times]
import protobuf_serialization
import protobuf_serialization/files/type_generator
import common/nngbind

import_proto3 "../../proto/m0.proto"

const port = 19500
let certs = getCurrentDir() / "tests" / "certs"
var stop: Atomic[bool]
var serverReady: Atomic[bool]

proc pem(name: string): string = readFile(certs / name)

proc tlsConfig(server: bool; cert, ca: string; hostname = ""): ptr nng_tls_config =
  var c: ptr nng_tls_config
  doAssert nng_tls_config_alloc(addr c, if server: NNG_TLS_MODE_SERVER else: NNG_TLS_MODE_CLIENT) == 0
  doAssert nng_tls_config_ca_chain(c, pem(ca).cstring, nil) == 0
  if cert.len > 0:
    doAssert nng_tls_config_own_cert(c, pem(cert & ".pem").cstring, pem(cert & ".key").cstring, nil) == 0
  doAssert nng_tls_config_auth_mode(c, NNG_TLS_AUTH_MODE_REQUIRED) == 0
  if hostname.len > 0: doAssert nng_tls_config_server_name(c, hostname.cstring) == 0
  c

# RAII for the socket (E-003): closes on destroy
type Sock = object
  s: nng_socket
  own: bool
proc `=destroy`(x: Sock) =
  if x.own: discard nng_close(x.s)
proc `=copy`(a: var Sock; b: Sock) {.error.}

proc serverLoop(unused: int) {.thread.} =
  var rep = Sock(own: true)
  doAssert nng_rep0_open(addr rep.s) == 0
  doAssert nng_socket_set_size(rep.s, NNG_OPT_RECVMAXSZ, 1024) == 0   # E-003: bounded messages
  doAssert nng_socket_set_ms(rep.s, NNG_OPT_RECVTIMEO, 200) == 0
  var l: nng_listener
  doAssert nng_listener_create(addr l, rep.s, cstring("tls+tcp://127.0.0.1:" & $port)) == 0
  var cfg: ptr nng_tls_config
  {.cast(gcsafe).}: cfg = tlsConfig(true, "server", "ca.pem")
  doAssert nng_listener_set_ptr(l, NNG_OPT_TLS_CONFIG, cfg) == 0
  nng_tls_config_free(cfg)
  doAssert nng_listener_start(l, 0) == 0
  serverReady.store(true)
  while not stop.load:
    var msg: ptr nng_msg
    if nng_recvmsg(rep.s, addr msg, 0) != 0: continue
    let body = newString(nng_msg_len(msg))
    if body.len > 0: copyMem(unsafeAddr body[0], nng_msg_body(msg), body.len)
    var reply = ""
    if body == "who":
      var cn: cstring
      if nng_pipe_get_string(nng_msg_get_pipe(msg), NNG_OPT_TLS_PEER_CN, cast[cstringArray](addr cn)) == 0:
        reply = "cn=" & $cn
        nng_strfree(cn)
    elif body.startsWith("pb:"):   # a Protobuf message: bump n
      let m = Protobuf.decode(cast[seq[byte]](body[3 .. ^1]), Inner)
      let enc = Protobuf.encode(Inner(name: m.name, n: m.n + 1))
      reply = "pb:"
      for b in enc: reply.add char(b)
    else: reply = body
    nng_msg_free(msg)
    discard nng_send(rep.s, reply.cstring, reply.len.csize_t, 0)

proc client(cert, ca: string; timeoutMs = 2000): Sock =
  result = Sock(own: true)
  doAssert nng_req0_open(addr result.s) == 0
  discard nng_socket_set_ms(result.s, NNG_OPT_RECVTIMEO, timeoutMs.cint)
  discard nng_socket_set_ms(result.s, NNG_OPT_SENDTIMEO, timeoutMs.cint)
  var d: nng_dialer
  if nng_dialer_create(addr d, result.s, cstring("tls+tcp://localhost:" & $port)) != 0: return
  let cfg = tlsConfig(false, cert, ca, "localhost")
  discard nng_dialer_set_ptr(d, NNG_OPT_TLS_CONFIG, cfg)
  nng_tls_config_free(cfg)
  discard nng_dialer_start(d, 0)

proc request(c: Sock; m: string): tuple[ok: bool, body: string] =
  if nng_send(c.s, m.cstring, m.len.csize_t, 0) != 0: return (false, "")
  var buf: pointer
  var sz: csize_t
  if nng_recv(c.s, cast[pointer](addr buf), addr sz, NNG_FLAG_ALLOC.cint) != 0: return (false, "")
  result = (true, newString(sz))
  if sz > 0: copyMem(addr result.body[0], buf, sz)
  nng_free(buf, sz)

proc rssNow(): int = parseInt(readFile("/proc/self/statm").splitWhitespace()[1]) * 4096

suite "chosen transport: NNG via generated bindings (ADR 0010)":
  var th: Thread[int]
  createThread(th, serverLoop, 0)
  while not serverReady.load: sleep 20

  test "mTLS request/reply works and the server sees the client identity (certificate CN)":
    let c = client("client", "ca.pem")
    check c.request("hello") == (true, "hello")
    check c.request("who") == (true, "cn=scheduler-1")

  test "no certificate, foreign-CA certificate and untrusted server are rejected":
    check not client("", "ca.pem", 1200).request("x").ok
    check not client("rogue", "ca.pem", 1200).request("x").ok
    check not client("client", "rogue-ca.pem", 1200).request("x").ok

  test "E-003 receive size limit: a message above the limit is refused, a normal one still works":
    let c = client("client", "ca.pem", 1500)
    check c.request("y".repeat(100)).ok
    let big = client("client", "ca.pem", 1500)
    check not big.request("z".repeat(4096)).ok
    check client("client", "ca.pem").request("still up") == (true, "still up")

  test "Protobuf message round trip over NNG":
    let c = client("client", "ca.pem")
    let bytes = Protobuf.encode(Inner(name: "step-7", n: 41))
    var msg = "pb:"
    for b in bytes: msg.add char(b)
    let r = c.request(msg)
    check r.ok and r.body.startsWith("pb:")
    let got = Protobuf.decode(cast[seq[byte]](r.body[3 .. ^1]), Inner)
    check got.name == "step-7" and got.n == 42

  test "2000 request/reply round trips are correct":
    let c = client("client", "ca.pem")
    var ok = 0
    let t0 = epochTime()
    for i in 0 ..< 2000:
      if c.request("m" & $i) == (true, "m" & $i): inc ok
    echo "  METRIC req_per_s = ", int(2000.0 / (epochTime() - t0))
    check ok == 2000

  test "E-003 connect/close cycles: Nim heap and process RSS stay flat":
    proc cycle() =
      let c = client("client", "ca.pem", 3000)
      discard c.request("x")
    for _ in 0 ..< 2000: cycle()   # warm-up: allocator arenas and thread caches settle
    let h0 = getOccupiedMem()
    var windows: seq[int]
    for _ in 0 ..< parseInt(getEnv("CINIM_WINDOWS", "3")):
      let r0 = rssNow()
      for _ in 0 ..< 1000: cycle()
      windows.add (rssNow() - r0) div 1000
    echo "  METRIC rss_bytes_per_connection_by_window = ", windows
    let perConn = windows[^1]
    echo "  METRIC nim_heap_growth_bytes = ", getOccupiedMem() - h0
    when not defined(sanitize): check perConn < 64
    check getOccupiedMem() - h0 < 8192

  test "shutdown is clean":
    stop.store(true)
    joinThread(th)
