# Generated by tools/http/gen.sh (c2nim) from civetweb.h. Do not edit.
const civetHeader = "civetweb.h"
type
  uint8_t* = uint8
  uint16_t* = uint16
  uint32_t* = uint32
  uint64_t* = uint64
  int64_t* = int64
  time_t* = int64
  mg_context* {.importc: "struct mg_context", header: civetHeader, incompleteStruct.} = object
  mg_connection* {.importc: "struct mg_connection", header: civetHeader, incompleteStruct.} = object
  mg_client_cert* {.importc: "struct mg_client_cert", header: civetHeader, incompleteStruct.} = object
const
  MG_MAX_HEADERS* = (64)

type
  mg_header* {.importc: "struct mg_header", header: civetHeader, bycopy.} = object
    name* {.importc: "name".}: cstring
    value* {.importc: "value".}: cstring

  mg_request_info* {.importc: "struct mg_request_info", header: civetHeader, bycopy.} = object
    request_method* {.importc: "request_method".}: cstring
    request_uri* {.importc: "request_uri".}: cstring
    local_uri_raw* {.importc: "local_uri_raw".}: cstring
    local_uri* {.importc: "local_uri".}: cstring
    http_version* {.importc: "http_version".}: cstring
    query_string* {.importc: "query_string".}: cstring
    remote_user* {.importc: "remote_user".}: cstring
    remote_addr* {.importc: "remote_addr".}: array[48, char]
    content_length* {.importc: "content_length".}: clonglong
    remote_port* {.importc: "remote_port".}: cint
    server_port* {.importc: "server_port".}: cint
    is_ssl* {.importc: "is_ssl".}: cint
    user_data* {.importc: "user_data".}: pointer
    conn_data* {.importc: "conn_data".}: pointer
    num_headers* {.importc: "num_headers".}: cint
    http_headers* {.importc: "http_headers".}: array[MG_MAX_HEADERS, mg_header]
    client_cert* {.importc: "client_cert".}: ptr mg_client_cert
    acceptedWebSocketSubprotocol* {.importc: "acceptedWebSocketSubprotocol".}: cstring

  mg_callbacks* {.importc: "struct mg_callbacks", header: civetHeader, bycopy.} = object
    begin_request* {.importc: "begin_request".}: proc (a1: ptr mg_connection): cint {.
        cdecl.}
    end_request* {.importc: "end_request".}: proc (a1: ptr mg_connection;
        reply_status_code: cint) {.cdecl.}
    log_message* {.importc: "log_message".}: proc (a1: ptr mg_connection;
        message: cstring): cint {.cdecl.}
    log_access* {.importc: "log_access".}: proc (a1: ptr mg_connection;
        message: cstring): cint {.cdecl.}
    init_ssl* {.importc: "init_ssl".}: proc (ssl_ctx: pointer; user_data: pointer): cint {.
        cdecl.}
    init_ssl_domain* {.importc: "init_ssl_domain".}: proc (server_domain: cstring;
        ssl_ctx: pointer; user_data: pointer): cint {.cdecl.}
    external_ssl_ctx* {.importc: "external_ssl_ctx".}: proc (ssl_ctx: ptr pointer;
        user_data: pointer): cint {.cdecl.}
    external_ssl_ctx_domain* {.importc: "external_ssl_ctx_domain".}: proc (
        server_domain: cstring; ssl_ctx: ptr pointer; user_data: pointer): cint {.cdecl.}
    connection_close* {.importc: "connection_close".}: proc (a1: ptr mg_connection) {.
        cdecl.}
    connection_closed* {.importc: "connection_closed".}: proc (a1: ptr mg_connection) {.
        cdecl.}
    init_lua* {.importc: "init_lua".}: proc (conn: ptr mg_connection;
        lua_context: pointer; context_flags: cuint) {.cdecl.}
    exit_lua* {.importc: "exit_lua".}: proc (conn: ptr mg_connection;
        lua_context: pointer; context_flags: cuint) {.cdecl.}
    http_error* {.importc: "http_error".}: proc (conn: ptr mg_connection; status: cint;
        errmsg: cstring): cint {.cdecl.}
    init_context* {.importc: "init_context".}: proc (ctx: ptr mg_context) {.cdecl.}
    exit_context* {.importc: "exit_context".}: proc (ctx: ptr mg_context) {.cdecl.}
    init_thread* {.importc: "init_thread".}: proc (ctx: ptr mg_context;
        thread_type: cint): pointer {.cdecl.}
    exit_thread* {.importc: "exit_thread".}: proc (ctx: ptr mg_context;
        thread_type: cint; thread_pointer: pointer) {.cdecl.}
    init_connection* {.importc: "init_connection".}: proc (conn: ptr mg_connection;
        conn_data: ptr pointer): cint {.cdecl.}

  mg_request_handler* = proc (conn: ptr mg_connection; cbdata: pointer): cint {.cdecl.}

proc mg_init_library*(features: cuint): cuint {.cdecl, importc: "mg_init_library",
    header: civetHeader.}
proc mg_exit_library*(): cuint {.cdecl, importc: "mg_exit_library",
                              header: civetHeader.}
proc mg_start*(callbacks: ptr mg_callbacks; user_data: pointer;
              configuration_options: cstringArray): ptr mg_context {.cdecl,
    importc: "mg_start", header: civetHeader.}
proc mg_stop*(a1: ptr mg_context) {.cdecl, importc: "mg_stop", header: civetHeader.}
proc mg_set_request_handler*(ctx: ptr mg_context; uri: cstring;
                            handler: mg_request_handler; cbdata: pointer) {.cdecl,
    importc: "mg_set_request_handler", header: civetHeader.}
proc mg_get_request_info*(a1: ptr mg_connection): ptr mg_request_info {.cdecl,
    importc: "mg_get_request_info", header: civetHeader.}
proc mg_get_user_data*(ctx: ptr mg_context): pointer {.cdecl,
    importc: "mg_get_user_data", header: civetHeader.}
proc mg_get_context*(conn: ptr mg_connection): ptr mg_context {.cdecl,
    importc: "mg_get_context", header: civetHeader.}
proc mg_write*(a1: ptr mg_connection; buf: pointer; len: csize_t): cint {.cdecl,
    importc: "mg_write", header: civetHeader.}
proc mg_printf*(a1: ptr mg_connection; fmt: cstring): cint {.varargs, cdecl,
    importc: "mg_printf", header: civetHeader.}
proc mg_read*(a1: ptr mg_connection; buf: pointer; len: csize_t): cint {.cdecl,
    importc: "mg_read", header: civetHeader.}
proc mg_send_http_error*(conn: ptr mg_connection; status_code: cint; fmt: cstring): cint {.
    varargs, cdecl, importc: "mg_send_http_error", header: civetHeader.}
proc mg_send_http_ok*(conn: ptr mg_connection; mime_type: cstring;
                     content_length: clonglong): cint {.cdecl,
    importc: "mg_send_http_ok", header: civetHeader.}
proc mg_response_header_start*(conn: ptr mg_connection; status: cint): cint {.cdecl,
    importc: "mg_response_header_start", header: civetHeader.}
proc mg_response_header_add*(conn: ptr mg_connection; header: cstring; value: cstring;
                            value_len: cint): cint {.cdecl,
    importc: "mg_response_header_add", header: civetHeader.}
proc mg_response_header_send*(conn: ptr mg_connection): cint {.cdecl,
    importc: "mg_response_header_send", header: civetHeader.}
proc mg_get_header*(a1: ptr mg_connection; name: cstring): cstring {.cdecl,
    importc: "mg_get_header", header: civetHeader.}
proc mg_send_chunk*(conn: ptr mg_connection; chunk: cstring; chunk_len: cuint): cint {.
    cdecl, importc: "mg_send_chunk", header: civetHeader.}
proc mg_lock_connection*(conn: ptr mg_connection) {.cdecl,
    importc: "mg_lock_connection", header: civetHeader.}
proc mg_unlock_connection*(conn: ptr mg_connection) {.cdecl,
    importc: "mg_unlock_connection", header: civetHeader.}