## Contract tests for proto v0 (section 18: "общие тестовые векторы Protobuf с Go и Python").
## Vectors come from Google's Python implementation on code generated by protoc from the real .proto files (tools/proto/gen_vectors.py).
## Run tools/proto/nim_flatten.sh build/nimproto first (nimble task testcontract does it).
import std/[unittest, json, strutils]
import protobuf_serialization
import protobuf_serialization/files/type_generator

import_proto3 "../../build/nimproto/all.proto"

const vectors = staticRead("../vectors/proto_v0.json")
let V = parseJson(vectors)

proc unhex(s: string): seq[byte] =
  for i in countup(0, s.len - 2, 2): result.add byte(parseHexInt(s[i .. i + 1]))
proc hex(b: openArray[byte]): string =
  for x in b: result.add toHex(int(x), 2).toLowerAscii
proc vec(name: string): seq[byte] = unhex(V[name].getStr)

func bytesOf(n: int): seq[byte] =
  for i in 0 ..< n: result.add byte(i)

suite "proto v0 wire compatibility with the reference implementation":
  test "StepReport: built in Nim encodes byte-for-byte like Python (map, negative int32, bytes)":
    let r = StepReport(header: Header(protocol: 1, request_id: "req-1"),
      step: StepRef(run_id: "sh1_0192f0a4", seq: 7, attempt: 2), job_token: "tok", exit_code: -1, reason: "env_rejected",
      outputs: @[OutputsEntry(key: "A", value: "b"), OutputsEntry(key: "VERSION", value: "1.2")],
      outputs_digest: bytesOf(32))
    check hex(Protobuf.encode(r)) == V["step_report"].getStr

  test "JournalEntry: uint64 max and bytes fields":
    let e = JournalEntry(seq: high(uint64), kind: "sh", payload: cast[seq[byte]]("{\"cmd\":\"make\"}"),
                         result: cast[seq[byte]]("{\"code\":0}"), hash: bytesOf(32))
    check hex(Protobuf.encode(e)) == V["journal_entry"].getStr
    check Protobuf.decode(vec("journal_entry"), JournalEntry).seq == high(uint64)

  test "ClusterState: enums, repeated messages, bool":
    let c = ClusterState(header: Header(protocol: 1), launch_gate_open: false, gate_reason: "no master",
      nodes: @[LogNode(node_id: "z1", address: "10.0.0.1:4080", role: NODE_ROLE_MASTER, health: NODE_HEALTH_UP, lag: 42),
               LogNode(node_id: "z2", address: "10.0.0.2:4080", role: NODE_ROLE_REPLICA, health: NODE_HEALTH_RESTORING, lag: 0)])
    check hex(Protobuf.encode(c)) == V["cluster_state"].getStr

  test "every reference vector decodes and re-encodes to the same bytes":
    check hex(Protobuf.encode(Protobuf.decode(vec("step_report"), StepReport))) == V["step_report"].getStr
    check hex(Protobuf.encode(Protobuf.decode(vec("log_batch"), LogBatch))) == V["log_batch"].getStr
    check hex(Protobuf.encode(Protobuf.decode(vec("poll_response"), PollResponse))) == V["poll_response"].getStr
    check hex(Protobuf.encode(Protobuf.decode(vec("journal_entry"), JournalEntry))) == V["journal_entry"].getStr
    check hex(Protobuf.encode(Protobuf.decode(vec("cluster_state"), ClusterState))) == V["cluster_state"].getStr

  test "LogBatch: timestamps, bytes and fixed32 survive":
    let b = Protobuf.decode(vec("log_batch"), LogBatch)
    check b.chunks.len == 2
    check b.chunks[0].crc32c == 0xDEADBEEF'u32 and b.chunks[0].data == cast[seq[byte]]("hello\n")
    check b.chunks[1].stream == LOG_STREAM_STDERR and b.chunks[1].data == @[0'u8, 255, 10]
    check b.header.sent_at.seconds == 1789980000 and b.header.sent_at.nanos == 123456789

  test "ControllerAttach: oneof commands (start, cancel, gate) keep their variant":
    let p = Protobuf.decode(vec("poll_response"), PollResponse)
    check p.commands.len == 3
    check p.commands[0].body.kind == CommandBodyKind.start and p.commands[0].body.start.image == "busybox:1.36"
    check p.commands[0].body.start.command == @["sh", "-c", "true"]
    check p.commands[1].body.kind == CommandBodyKind.cancel and p.commands[1].body.cancel.grace_seconds == 30
    check p.commands[2].body.kind == CommandBodyKind.gate and not p.commands[2].body.gate.open
    check p.commands[2].body.gate.reason == "logs_unavailable"

  test "plugin.v1 (PLG-008): a Struct-typed field carried as bytes is wire-identical (Nim codec cannot compile recursive Struct)":
    let e = Protobuf.decode(vec("execute_step"), ExecuteStep)
    check e.protocol == 1 and e.step_id == "s1" and e.workspace == "/cicd/workspace"
    check e.inputs.len > 0                                   # the encoded google.protobuf.Struct, untouched
    # Nim writes fields in declaration order (protocol = 5 comes first, as in PLG-008), protoc in field-number order:
    # both are valid Protobuf, so equality is checked on content, never on bytes. Hashes and signatures must not cover Protobuf bytes.
    let back = Protobuf.decode(Protobuf.encode(e), ExecuteStep)
    check back.protocol == e.protocol and back.step_id == e.step_id and back.workspace == e.workspace
    check back.inputs == e.inputs and back.secret_handles.len == 1 and back.secret_handles[0].key == "token"

  test "N/N-1: fields added by a newer sender are skipped":
    let r = Protobuf.decode(vec("step_report_future"), StepReport)
    check r.reason == "env_rejected" and r.exit_code == -1 and r.step.attempt == 2
    check hex(Protobuf.encode(r)) == V["step_report"].getStr    # the unknown fields are dropped, the rest is intact
