{{- if eq .Values.mode "multi" }}
apiVersion: v1
kind: Secret
metadata:
  name: cinim-router-key
  namespace: {{ include "cinim-shard.ns" . }}
type: Opaque
stringData:
  CINIM_ROUTER_KEY: {{ required "routerKey is required in the multi mode" .Values.routerKey | quote }}
{{- end }}
