# Generated by tools/nng/gen.sh (c2nim) from nng/nng.h. Do not edit.
const nngHeader = "nng/nng.h"
type
  uint8_t* = uint8
  uint16_t* = uint16
  uint32_t* = uint32
  uint64_t* = uint64
  int32_t* = int32
  int64_t* = int64
type nng_aio* {.importc: "nng_aio", header: nngHeader, incompleteStruct.} = object
type nng_cv* {.importc: "nng_cv", header: nngHeader, incompleteStruct.} = object
type nng_msg* {.importc: "nng_msg", header: nngHeader, incompleteStruct.} = object
type nng_mtx* {.importc: "nng_mtx", header: nngHeader, incompleteStruct.} = object
type nng_stat* {.importc: "nng_stat", header: nngHeader, incompleteStruct.} = object
type nng_stream* {.importc: "nng_stream", header: nngHeader, incompleteStruct.} = object
type nng_stream_dialer* {.importc: "nng_stream_dialer", header: nngHeader, incompleteStruct.} = object
type nng_stream_listener* {.importc: "nng_stream_listener", header: nngHeader, incompleteStruct.} = object
type nng_thread* {.importc: "nng_thread", header: nngHeader, incompleteStruct.} = object
type nng_udp* {.importc: "nng_udp", header: nngHeader, incompleteStruct.} = object




const
  NNG_MAJOR_VERSION* = 1
  NNG_MINOR_VERSION* = 12
  NNG_PATCH_VERSION* = 4


const
  NNG_RELEASE_SUFFIX* = ""


const
  NNG_MAXADDRLEN* = (128)


template NNG_PROTOCOL_NUMBER*(maj, min: untyped): untyped =
  (((x) * 16) + (y))


type
  nng_ctx* {.importc: "nng_ctx", header: nngHeader, bycopy.} = object
    id* {.importc: "id".}: uint32_t

  nng_dialer* {.importc: "nng_dialer", header: nngHeader, bycopy.} = object
    id* {.importc: "id".}: uint32_t

  nng_listener* {.importc: "nng_listener", header: nngHeader, bycopy.} = object
    id* {.importc: "id".}: uint32_t

  nng_pipe* {.importc: "nng_pipe", header: nngHeader, bycopy.} = object
    id* {.importc: "id".}: uint32_t

  nng_socket* {.importc: "nng_socket", header: nngHeader, bycopy.} = object
    id* {.importc: "id".}: uint32_t

  nng_duration* = int32_t


type
  nng_time* = uint64_t


const
  NNG_PIPE_INITIALIZER* = (0,)
  NNG_SOCKET_INITIALIZER* = (0,)
  NNG_DIALER_INITIALIZER* = (0,)
  NNG_LISTENER_INITIALIZER* = (0,)
  NNG_CTX_INITIALIZER* = (0,)


type
  nng_sockaddr_inproc* {.importc: "nng_sockaddr_inproc", header: nngHeader, bycopy.} = object
    sa_family* {.importc: "sa_family".}: uint16_t
    sa_name* {.importc: "sa_name".}: array[NNG_MAXADDRLEN, char]

  nng_sockaddr_path* {.importc: "nng_sockaddr_path", header: nngHeader, bycopy.} = object
    sa_family* {.importc: "sa_family".}: uint16_t
    sa_path* {.importc: "sa_path".}: array[NNG_MAXADDRLEN, char]

  nng_sockaddr_in6* {.importc: "nng_sockaddr_in6", header: nngHeader, bycopy.} = object
    sa_family* {.importc: "sa_family".}: uint16_t
    sa_port* {.importc: "sa_port".}: uint16_t
    sa_addr* {.importc: "sa_addr".}: array[16, uint8_t]
    sa_scope* {.importc: "sa_scope".}: uint32_t

  nng_sockaddr_in* {.importc: "nng_sockaddr_in", header: nngHeader, bycopy.} = object
    sa_family* {.importc: "sa_family".}: uint16_t
    sa_port* {.importc: "sa_port".}: uint16_t
    sa_addr* {.importc: "sa_addr".}: uint32_t

  nng_sockaddr_zt* {.importc: "nng_sockaddr_zt", header: nngHeader, bycopy.} = object
    sa_family* {.importc: "sa_family".}: uint16_t
    sa_nwid* {.importc: "sa_nwid".}: uint64_t
    sa_nodeid* {.importc: "sa_nodeid".}: uint64_t
    sa_port* {.importc: "sa_port".}: uint32_t

  nng_sockaddr_abstract* {.importc: "nng_sockaddr_abstract", header: nngHeader,
                          bycopy.} = object
    sa_family* {.importc: "sa_family".}: uint16_t
    sa_len* {.importc: "sa_len".}: uint16_t
    sa_name* {.importc: "sa_name".}: array[107, uint8_t]



type
  nng_sockaddr_storage* {.importc: "nng_sockaddr_storage", header: nngHeader, bycopy.} = object
    sa_family* {.importc: "sa_family".}: uint16_t
    sa_pad* {.importc: "sa_pad".}: array[16, uint64_t]

  nng_sockaddr_ipc* = nng_sockaddr_path
  nng_sockaddr* {.importc: "nng_sockaddr", header: nngHeader, bycopy, union.} = object
    s_family* {.importc: "s_family".}: uint16_t
    s_ipc* {.importc: "s_ipc".}: nng_sockaddr_ipc
    s_inproc* {.importc: "s_inproc".}: nng_sockaddr_inproc
    s_in6* {.importc: "s_in6".}: nng_sockaddr_in6
    s_in* {.importc: "s_in".}: nng_sockaddr_in
    s_zt* {.importc: "s_zt".}: nng_sockaddr_zt
    s_abstract* {.importc: "s_abstract".}: nng_sockaddr_abstract
    s_storage* {.importc: "s_storage".}: nng_sockaddr_storage

  nng_sockaddr_family* {.size: sizeof(cint).} = enum
    NNG_AF_UNSPEC = 0, NNG_AF_INPROC = 1, NNG_AF_IPC = 2, NNG_AF_INET = 3, NNG_AF_INET6 = 4,
    NNG_AF_ZT = 5, NNG_AF_ABSTRACT = 6



type
  nng_iov* {.importc: "nng_iov", header: nngHeader, bycopy.} = object
    iov_buf* {.importc: "iov_buf".}: pointer
    iov_len* {.importc: "iov_len".}: csize_t



const
  NNG_DURATION_INFINITE* = (-1)
  NNG_DURATION_DEFAULT* = (-2)
  NNG_DURATION_ZERO* = (0)


proc nng_fini*() {.cdecl, importc: "nng_fini", header: nngHeader.}

proc nng_close*(a1: nng_socket): cint {.cdecl, importc: "nng_close", header: nngHeader.}

proc nng_socket_close*(a1: nng_socket): cint {.cdecl, importc: "nng_socket_close",
    header: nngHeader.}

proc nng_socket_id*(a1: nng_socket): cint {.cdecl, importc: "nng_socket_id",
                                        header: nngHeader.}
proc nng_socket_set*(a1: nng_socket; a2: cstring; a3: pointer; a4: csize_t): cint {.cdecl,
    importc: "nng_socket_set", header: nngHeader.}
proc nng_socket_set_bool*(a1: nng_socket; a2: cstring; a3: bool): cint {.cdecl,
    importc: "nng_socket_set_bool", header: nngHeader.}
proc nng_socket_set_int*(a1: nng_socket; a2: cstring; a3: cint): cint {.cdecl,
    importc: "nng_socket_set_int", header: nngHeader.}
proc nng_socket_set_size*(a1: nng_socket; a2: cstring; a3: csize_t): cint {.cdecl,
    importc: "nng_socket_set_size", header: nngHeader.}
proc nng_socket_set_uint64*(a1: nng_socket; a2: cstring; a3: uint64_t): cint {.cdecl,
    importc: "nng_socket_set_uint64", header: nngHeader.}
proc nng_socket_set_string*(a1: nng_socket; a2: cstring; a3: cstring): cint {.cdecl,
    importc: "nng_socket_set_string", header: nngHeader.}
proc nng_socket_set_ptr*(a1: nng_socket; a2: cstring; a3: pointer): cint {.cdecl,
    importc: "nng_socket_set_ptr", header: nngHeader.}
proc nng_socket_set_ms*(a1: nng_socket; a2: cstring; a3: nng_duration): cint {.cdecl,
    importc: "nng_socket_set_ms", header: nngHeader.}
proc nng_socket_set_addr*(a1: nng_socket; a2: cstring; a3: ptr nng_sockaddr): cint {.
    cdecl, importc: "nng_socket_set_addr", header: nngHeader.}
proc nng_socket_get*(a1: nng_socket; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
    cdecl, importc: "nng_socket_get", header: nngHeader.}
proc nng_socket_get_bool*(a1: nng_socket; a2: cstring; a3: ptr bool): cint {.cdecl,
    importc: "nng_socket_get_bool", header: nngHeader.}
proc nng_socket_get_int*(a1: nng_socket; a2: cstring; a3: ptr cint): cint {.cdecl,
    importc: "nng_socket_get_int", header: nngHeader.}
proc nng_socket_get_size*(a1: nng_socket; a2: cstring; a3: ptr csize_t): cint {.cdecl,
    importc: "nng_socket_get_size", header: nngHeader.}
proc nng_socket_get_uint64*(a1: nng_socket; a2: cstring; a3: ptr uint64_t): cint {.cdecl,
    importc: "nng_socket_get_uint64", header: nngHeader.}
proc nng_socket_get_string*(a1: nng_socket; a2: cstring; a3: cstringArray): cint {.
    cdecl, importc: "nng_socket_get_string", header: nngHeader.}
proc nng_socket_get_ptr*(a1: nng_socket; a2: cstring; a3: ptr pointer): cint {.cdecl,
    importc: "nng_socket_get_ptr", header: nngHeader.}
proc nng_socket_get_ms*(a1: nng_socket; a2: cstring; a3: ptr nng_duration): cint {.cdecl,
    importc: "nng_socket_get_ms", header: nngHeader.}
proc nng_socket_get_addr*(a1: nng_socket; a2: cstring; a3: ptr nng_sockaddr): cint {.
    cdecl, importc: "nng_socket_get_addr", header: nngHeader.}

proc nng_socket_proto_id*(id: nng_socket; a2: ptr uint16_t): cint {.cdecl,
    importc: "nng_socket_proto_id", header: nngHeader.}
proc nng_socket_peer_id*(id: nng_socket; a2: ptr uint16_t): cint {.cdecl,
    importc: "nng_socket_peer_id", header: nngHeader.}
proc nng_socket_proto_name*(id: nng_socket; a2: cstringArray): cint {.cdecl,
    importc: "nng_socket_proto_name", header: nngHeader.}
proc nng_socket_peer_name*(id: nng_socket; a2: cstringArray): cint {.cdecl,
    importc: "nng_socket_peer_name", header: nngHeader.}
proc nng_socket_raw*(a1: nng_socket; a2: ptr bool): cint {.cdecl,
    importc: "nng_socket_raw", header: nngHeader.}

const
  NNG_MAXADDRSTRLEN* = 144

proc nng_str_sockaddr*(sa: ptr nng_sockaddr; buf: cstring; bufsz: csize_t): cstring {.
    cdecl, importc: "nng_str_sockaddr", header: nngHeader.}

type
  nng_pipe_ev* {.size: sizeof(cint).} = enum
    NNG_PIPE_EV_ADD_PRE, NNG_PIPE_EV_ADD_POST, NNG_PIPE_EV_REM_POST,
    NNG_PIPE_EV_NUM
  nng_pipe_cb* = proc (a1: nng_pipe; a2: nng_pipe_ev; a3: pointer) {.cdecl.}



proc nng_pipe_notify*(a1: nng_socket; a2: nng_pipe_ev; a3: nng_pipe_cb; a4: pointer): cint {.
    cdecl, importc: "nng_pipe_notify", header: nngHeader.}

proc nng_listen*(a1: nng_socket; a2: cstring; a3: ptr nng_listener; a4: cint): cint {.
    cdecl, importc: "nng_listen", header: nngHeader.}

proc nng_dial*(a1: nng_socket; a2: cstring; a3: ptr nng_dialer; a4: cint): cint {.cdecl,
    importc: "nng_dial", header: nngHeader.}

proc nng_dialer_create*(a1: ptr nng_dialer; a2: nng_socket; a3: cstring): cint {.cdecl,
    importc: "nng_dialer_create", header: nngHeader.}

proc nng_listener_create*(a1: ptr nng_listener; a2: nng_socket; a3: cstring): cint {.
    cdecl, importc: "nng_listener_create", header: nngHeader.}

proc nng_dialer_start*(a1: nng_dialer; a2: cint): cint {.cdecl,
    importc: "nng_dialer_start", header: nngHeader.}

proc nng_listener_start*(a1: nng_listener; a2: cint): cint {.cdecl,
    importc: "nng_listener_start", header: nngHeader.}

proc nng_dialer_close*(a1: nng_dialer): cint {.cdecl, importc: "nng_dialer_close",
    header: nngHeader.}

proc nng_listener_close*(a1: nng_listener): cint {.cdecl,
    importc: "nng_listener_close", header: nngHeader.}

proc nng_dialer_id*(a1: nng_dialer): cint {.cdecl, importc: "nng_dialer_id",
                                        header: nngHeader.}

proc nng_listener_id*(a1: nng_listener): cint {.cdecl, importc: "nng_listener_id",
    header: nngHeader.}
proc nng_dialer_set*(a1: nng_dialer; a2: cstring; a3: pointer; a4: csize_t): cint {.cdecl,
    importc: "nng_dialer_set", header: nngHeader.}
proc nng_dialer_set_bool*(a1: nng_dialer; a2: cstring; a3: bool): cint {.cdecl,
    importc: "nng_dialer_set_bool", header: nngHeader.}
proc nng_dialer_set_int*(a1: nng_dialer; a2: cstring; a3: cint): cint {.cdecl,
    importc: "nng_dialer_set_int", header: nngHeader.}
proc nng_dialer_set_size*(a1: nng_dialer; a2: cstring; a3: csize_t): cint {.cdecl,
    importc: "nng_dialer_set_size", header: nngHeader.}
proc nng_dialer_set_uint64*(a1: nng_dialer; a2: cstring; a3: uint64_t): cint {.cdecl,
    importc: "nng_dialer_set_uint64", header: nngHeader.}
proc nng_dialer_set_string*(a1: nng_dialer; a2: cstring; a3: cstring): cint {.cdecl,
    importc: "nng_dialer_set_string", header: nngHeader.}
proc nng_dialer_set_ptr*(a1: nng_dialer; a2: cstring; a3: pointer): cint {.cdecl,
    importc: "nng_dialer_set_ptr", header: nngHeader.}
proc nng_dialer_set_ms*(a1: nng_dialer; a2: cstring; a3: nng_duration): cint {.cdecl,
    importc: "nng_dialer_set_ms", header: nngHeader.}
proc nng_dialer_set_addr*(a1: nng_dialer; a2: cstring; a3: ptr nng_sockaddr): cint {.
    cdecl, importc: "nng_dialer_set_addr", header: nngHeader.}
proc nng_dialer_get*(a1: nng_dialer; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
    cdecl, importc: "nng_dialer_get", header: nngHeader.}
proc nng_dialer_get_bool*(a1: nng_dialer; a2: cstring; a3: ptr bool): cint {.cdecl,
    importc: "nng_dialer_get_bool", header: nngHeader.}
proc nng_dialer_get_int*(a1: nng_dialer; a2: cstring; a3: ptr cint): cint {.cdecl,
    importc: "nng_dialer_get_int", header: nngHeader.}
proc nng_dialer_get_size*(a1: nng_dialer; a2: cstring; a3: ptr csize_t): cint {.cdecl,
    importc: "nng_dialer_get_size", header: nngHeader.}
proc nng_dialer_get_uint64*(a1: nng_dialer; a2: cstring; a3: ptr uint64_t): cint {.cdecl,
    importc: "nng_dialer_get_uint64", header: nngHeader.}
proc nng_dialer_get_string*(a1: nng_dialer; a2: cstring; a3: cstringArray): cint {.
    cdecl, importc: "nng_dialer_get_string", header: nngHeader.}
proc nng_dialer_get_ptr*(a1: nng_dialer; a2: cstring; a3: ptr pointer): cint {.cdecl,
    importc: "nng_dialer_get_ptr", header: nngHeader.}
proc nng_dialer_get_ms*(a1: nng_dialer; a2: cstring; a3: ptr nng_duration): cint {.cdecl,
    importc: "nng_dialer_get_ms", header: nngHeader.}
proc nng_dialer_get_addr*(a1: nng_dialer; a2: cstring; a3: ptr nng_sockaddr): cint {.
    cdecl, importc: "nng_dialer_get_addr", header: nngHeader.}
proc nng_listener_set*(a1: nng_listener; a2: cstring; a3: pointer; a4: csize_t): cint {.
    cdecl, importc: "nng_listener_set", header: nngHeader.}
proc nng_listener_set_bool*(a1: nng_listener; a2: cstring; a3: bool): cint {.cdecl,
    importc: "nng_listener_set_bool", header: nngHeader.}
proc nng_listener_set_int*(a1: nng_listener; a2: cstring; a3: cint): cint {.cdecl,
    importc: "nng_listener_set_int", header: nngHeader.}
proc nng_listener_set_size*(a1: nng_listener; a2: cstring; a3: csize_t): cint {.cdecl,
    importc: "nng_listener_set_size", header: nngHeader.}
proc nng_listener_set_uint64*(a1: nng_listener; a2: cstring; a3: uint64_t): cint {.
    cdecl, importc: "nng_listener_set_uint64", header: nngHeader.}
proc nng_listener_set_string*(a1: nng_listener; a2: cstring; a3: cstring): cint {.cdecl,
    importc: "nng_listener_set_string", header: nngHeader.}
proc nng_listener_set_ptr*(a1: nng_listener; a2: cstring; a3: pointer): cint {.cdecl,
    importc: "nng_listener_set_ptr", header: nngHeader.}
proc nng_listener_set_ms*(a1: nng_listener; a2: cstring; a3: nng_duration): cint {.
    cdecl, importc: "nng_listener_set_ms", header: nngHeader.}
proc nng_listener_set_addr*(a1: nng_listener; a2: cstring; a3: ptr nng_sockaddr): cint {.
    cdecl, importc: "nng_listener_set_addr", header: nngHeader.}
proc nng_listener_get*(a1: nng_listener; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
    cdecl, importc: "nng_listener_get", header: nngHeader.}
proc nng_listener_get_bool*(a1: nng_listener; a2: cstring; a3: ptr bool): cint {.cdecl,
    importc: "nng_listener_get_bool", header: nngHeader.}
proc nng_listener_get_int*(a1: nng_listener; a2: cstring; a3: ptr cint): cint {.cdecl,
    importc: "nng_listener_get_int", header: nngHeader.}
proc nng_listener_get_size*(a1: nng_listener; a2: cstring; a3: ptr csize_t): cint {.
    cdecl, importc: "nng_listener_get_size", header: nngHeader.}
proc nng_listener_get_uint64*(a1: nng_listener; a2: cstring; a3: ptr uint64_t): cint {.
    cdecl, importc: "nng_listener_get_uint64", header: nngHeader.}
proc nng_listener_get_string*(a1: nng_listener; a2: cstring; a3: cstringArray): cint {.
    cdecl, importc: "nng_listener_get_string", header: nngHeader.}
proc nng_listener_get_ptr*(a1: nng_listener; a2: cstring; a3: ptr pointer): cint {.cdecl,
    importc: "nng_listener_get_ptr", header: nngHeader.}
proc nng_listener_get_ms*(a1: nng_listener; a2: cstring; a3: ptr nng_duration): cint {.
    cdecl, importc: "nng_listener_get_ms", header: nngHeader.}
proc nng_listener_get_addr*(a1: nng_listener; a2: cstring; a3: ptr nng_sockaddr): cint {.
    cdecl, importc: "nng_listener_get_addr", header: nngHeader.}

proc nng_strerror*(a1: cint): cstring {.cdecl, importc: "nng_strerror",
                                    header: nngHeader.}

proc nng_send*(a1: nng_socket; a2: pointer; a3: csize_t; a4: cint): cint {.cdecl,
    importc: "nng_send", header: nngHeader.}

proc nng_recv*(a1: nng_socket; a2: pointer; a3: ptr csize_t; a4: cint): cint {.cdecl,
    importc: "nng_recv", header: nngHeader.}

proc nng_sendmsg*(a1: nng_socket; a2: ptr nng_msg; a3: cint): cint {.cdecl,
    importc: "nng_sendmsg", header: nngHeader.}

proc nng_recvmsg*(a1: nng_socket; a2: ptr ptr nng_msg; a3: cint): cint {.cdecl,
    importc: "nng_recvmsg", header: nngHeader.}

proc nng_sock_send*(a1: nng_socket; a2: ptr nng_aio) {.cdecl, importc: "nng_sock_send",
    header: nngHeader.}

proc nng_send_aio*(a1: nng_socket; a2: ptr nng_aio) {.cdecl, importc: "nng_send_aio",
    header: nngHeader.}

proc nng_sock_recv*(a1: nng_socket; a2: ptr nng_aio) {.cdecl, importc: "nng_sock_recv",
    header: nngHeader.}

proc nng_recv_aio*(a1: nng_socket; a2: ptr nng_aio) {.cdecl, importc: "nng_recv_aio",
    header: nngHeader.}

proc nng_ctx_open*(a1: ptr nng_ctx; a2: nng_socket): cint {.cdecl,
    importc: "nng_ctx_open", header: nngHeader.}

proc nng_ctx_close*(a1: nng_ctx): cint {.cdecl, importc: "nng_ctx_close",
                                     header: nngHeader.}

proc nng_ctx_id*(a1: nng_ctx): cint {.cdecl, importc: "nng_ctx_id", header: nngHeader.}

proc nng_ctx_recv*(a1: nng_ctx; a2: ptr nng_aio) {.cdecl, importc: "nng_ctx_recv",
    header: nngHeader.}

proc nng_ctx_recvmsg*(a1: nng_ctx; a2: ptr ptr nng_msg; a3: cint): cint {.cdecl,
    importc: "nng_ctx_recvmsg", header: nngHeader.}

proc nng_ctx_send*(a1: nng_ctx; a2: ptr nng_aio) {.cdecl, importc: "nng_ctx_send",
    header: nngHeader.}

proc nng_ctx_sendmsg*(a1: nng_ctx; a2: ptr nng_msg; a3: cint): cint {.cdecl,
    importc: "nng_ctx_sendmsg", header: nngHeader.}
proc nng_ctx_get*(a1: nng_ctx; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.cdecl,
    importc: "nng_ctx_get", header: nngHeader.}
proc nng_ctx_get_bool*(a1: nng_ctx; a2: cstring; a3: ptr bool): cint {.cdecl,
    importc: "nng_ctx_get_bool", header: nngHeader.}
proc nng_ctx_get_int*(a1: nng_ctx; a2: cstring; a3: ptr cint): cint {.cdecl,
    importc: "nng_ctx_get_int", header: nngHeader.}
proc nng_ctx_get_size*(a1: nng_ctx; a2: cstring; a3: ptr csize_t): cint {.cdecl,
    importc: "nng_ctx_get_size", header: nngHeader.}
proc nng_ctx_get_uint64*(a1: nng_ctx; a2: cstring; a3: ptr uint64_t): cint {.cdecl,
    importc: "nng_ctx_get_uint64", header: nngHeader.}
proc nng_ctx_get_string*(a1: nng_ctx; a2: cstring; a3: cstringArray): cint {.cdecl,
    importc: "nng_ctx_get_string", header: nngHeader.}
proc nng_ctx_get_ptr*(a1: nng_ctx; a2: cstring; a3: ptr pointer): cint {.cdecl,
    importc: "nng_ctx_get_ptr", header: nngHeader.}
proc nng_ctx_get_ms*(a1: nng_ctx; a2: cstring; a3: ptr nng_duration): cint {.cdecl,
    importc: "nng_ctx_get_ms", header: nngHeader.}
proc nng_ctx_set*(a1: nng_ctx; a2: cstring; a3: pointer; a4: csize_t): cint {.cdecl,
    importc: "nng_ctx_set", header: nngHeader.}
proc nng_ctx_set_bool*(a1: nng_ctx; a2: cstring; a3: bool): cint {.cdecl,
    importc: "nng_ctx_set_bool", header: nngHeader.}
proc nng_ctx_set_int*(a1: nng_ctx; a2: cstring; a3: cint): cint {.cdecl,
    importc: "nng_ctx_set_int", header: nngHeader.}
proc nng_ctx_set_size*(a1: nng_ctx; a2: cstring; a3: csize_t): cint {.cdecl,
    importc: "nng_ctx_set_size", header: nngHeader.}
proc nng_ctx_set_uint64*(a1: nng_ctx; a2: cstring; a3: uint64_t): cint {.cdecl,
    importc: "nng_ctx_set_uint64", header: nngHeader.}
proc nng_ctx_set_string*(a1: nng_ctx; a2: cstring; a3: cstring): cint {.cdecl,
    importc: "nng_ctx_set_string", header: nngHeader.}
proc nng_ctx_set_ptr*(a1: nng_ctx; a2: cstring; a3: pointer): cint {.cdecl,
    importc: "nng_ctx_set_ptr", header: nngHeader.}
proc nng_ctx_set_ms*(a1: nng_ctx; a2: cstring; a3: nng_duration): cint {.cdecl,
    importc: "nng_ctx_set_ms", header: nngHeader.}

proc nng_alloc*(a1: csize_t): pointer {.cdecl, importc: "nng_alloc", header: nngHeader.}

proc nng_free*(a1: pointer; a2: csize_t) {.cdecl, importc: "nng_free", header: nngHeader.}

proc nng_strdup*(a1: cstring): cstring {.cdecl, importc: "nng_strdup",
                                     header: nngHeader.}

proc nng_strfree*(a1: cstring) {.cdecl, importc: "nng_strfree", header: nngHeader.}

proc nng_aio_alloc*(a1: ptr ptr nng_aio; a2: proc (a1: pointer) {.cdecl.}; a3: pointer): cint {.
    cdecl, importc: "nng_aio_alloc", header: nngHeader.}

proc nng_aio_free*(a1: ptr nng_aio) {.cdecl, importc: "nng_aio_free", header: nngHeader.}

proc nng_aio_reap*(a1: ptr nng_aio) {.cdecl, importc: "nng_aio_reap", header: nngHeader.}

proc nng_aio_stop*(a1: ptr nng_aio) {.cdecl, importc: "nng_aio_stop", header: nngHeader.}

proc nng_aio_result*(a1: ptr nng_aio): cint {.cdecl, importc: "nng_aio_result",
    header: nngHeader.}

proc nng_aio_count*(a1: ptr nng_aio): csize_t {.cdecl, importc: "nng_aio_count",
    header: nngHeader.}

proc nng_aio_cancel*(a1: ptr nng_aio) {.cdecl, importc: "nng_aio_cancel",
                                    header: nngHeader.}

proc nng_aio_abort*(a1: ptr nng_aio; a2: cint) {.cdecl, importc: "nng_aio_abort",
    header: nngHeader.}

proc nng_aio_wait*(a1: ptr nng_aio) {.cdecl, importc: "nng_aio_wait", header: nngHeader.}

proc nng_aio_busy*(a1: ptr nng_aio): bool {.cdecl, importc: "nng_aio_busy",
                                       header: nngHeader.}

proc nng_aio_set_msg*(a1: ptr nng_aio; a2: ptr nng_msg) {.cdecl,
    importc: "nng_aio_set_msg", header: nngHeader.}

proc nng_aio_get_msg*(a1: ptr nng_aio): ptr nng_msg {.cdecl,
    importc: "nng_aio_get_msg", header: nngHeader.}

proc nng_aio_set_input*(a1: ptr nng_aio; a2: cuint; a3: pointer): cint {.cdecl,
    importc: "nng_aio_set_input", header: nngHeader.}

proc nng_aio_get_input*(a1: ptr nng_aio; a2: cuint): pointer {.cdecl,
    importc: "nng_aio_get_input", header: nngHeader.}

proc nng_aio_set_output*(a1: ptr nng_aio; a2: cuint; a3: pointer): cint {.cdecl,
    importc: "nng_aio_set_output", header: nngHeader.}

proc nng_aio_get_output*(a1: ptr nng_aio; a2: cuint): pointer {.cdecl,
    importc: "nng_aio_get_output", header: nngHeader.}

proc nng_aio_set_timeout*(a1: ptr nng_aio; a2: nng_duration) {.cdecl,
    importc: "nng_aio_set_timeout", header: nngHeader.}

proc nng_aio_set_expire*(a1: ptr nng_aio; a2: nng_time) {.cdecl,
    importc: "nng_aio_set_expire", header: nngHeader.}

proc nng_aio_set_iov*(a1: ptr nng_aio; a2: cuint; a3: ptr nng_iov): cint {.cdecl,
    importc: "nng_aio_set_iov", header: nngHeader.}

proc nng_aio_begin*(a1: ptr nng_aio): bool {.cdecl, importc: "nng_aio_begin",
                                        header: nngHeader.}

proc nng_aio_finish*(a1: ptr nng_aio; a2: cint) {.cdecl, importc: "nng_aio_finish",
    header: nngHeader.}

type
  nng_aio_cancelfn* = proc (a1: ptr nng_aio; a2: pointer; a3: cint) {.cdecl.}

proc nng_aio_defer*(a1: ptr nng_aio; a2: nng_aio_cancelfn; a3: pointer) {.cdecl,
    importc: "nng_aio_defer", header: nngHeader.}

proc nng_sleep_aio*(a1: nng_duration; a2: ptr nng_aio) {.cdecl,
    importc: "nng_sleep_aio", header: nngHeader.}

proc nng_msg_alloc*(a1: ptr ptr nng_msg; a2: csize_t): cint {.cdecl,
    importc: "nng_msg_alloc", header: nngHeader.}
proc nng_msg_free*(a1: ptr nng_msg) {.cdecl, importc: "nng_msg_free", header: nngHeader.}
proc nng_msg_realloc*(a1: ptr nng_msg; a2: csize_t): cint {.cdecl,
    importc: "nng_msg_realloc", header: nngHeader.}
proc nng_msg_reserve*(a1: ptr nng_msg; a2: csize_t): cint {.cdecl,
    importc: "nng_msg_reserve", header: nngHeader.}
proc nng_msg_capacity*(a1: ptr nng_msg): csize_t {.cdecl, importc: "nng_msg_capacity",
    header: nngHeader.}
proc nng_msg_header*(a1: ptr nng_msg): pointer {.cdecl, importc: "nng_msg_header",
    header: nngHeader.}
proc nng_msg_header_len*(a1: ptr nng_msg): csize_t {.cdecl,
    importc: "nng_msg_header_len", header: nngHeader.}
proc nng_msg_body*(a1: ptr nng_msg): pointer {.cdecl, importc: "nng_msg_body",
    header: nngHeader.}
proc nng_msg_len*(a1: ptr nng_msg): csize_t {.cdecl, importc: "nng_msg_len",
    header: nngHeader.}
proc nng_msg_append*(a1: ptr nng_msg; a2: pointer; a3: csize_t): cint {.cdecl,
    importc: "nng_msg_append", header: nngHeader.}
proc nng_msg_insert*(a1: ptr nng_msg; a2: pointer; a3: csize_t): cint {.cdecl,
    importc: "nng_msg_insert", header: nngHeader.}
proc nng_msg_trim*(a1: ptr nng_msg; a2: csize_t): cint {.cdecl, importc: "nng_msg_trim",
    header: nngHeader.}
proc nng_msg_chop*(a1: ptr nng_msg; a2: csize_t): cint {.cdecl, importc: "nng_msg_chop",
    header: nngHeader.}
proc nng_msg_header_append*(a1: ptr nng_msg; a2: pointer; a3: csize_t): cint {.cdecl,
    importc: "nng_msg_header_append", header: nngHeader.}
proc nng_msg_header_insert*(a1: ptr nng_msg; a2: pointer; a3: csize_t): cint {.cdecl,
    importc: "nng_msg_header_insert", header: nngHeader.}
proc nng_msg_header_trim*(a1: ptr nng_msg; a2: csize_t): cint {.cdecl,
    importc: "nng_msg_header_trim", header: nngHeader.}
proc nng_msg_header_chop*(a1: ptr nng_msg; a2: csize_t): cint {.cdecl,
    importc: "nng_msg_header_chop", header: nngHeader.}
proc nng_msg_header_append_u16*(a1: ptr nng_msg; a2: uint16_t): cint {.cdecl,
    importc: "nng_msg_header_append_u16", header: nngHeader.}
proc nng_msg_header_append_u32*(a1: ptr nng_msg; a2: uint32_t): cint {.cdecl,
    importc: "nng_msg_header_append_u32", header: nngHeader.}
proc nng_msg_header_append_u64*(a1: ptr nng_msg; a2: uint64_t): cint {.cdecl,
    importc: "nng_msg_header_append_u64", header: nngHeader.}
proc nng_msg_header_insert_u16*(a1: ptr nng_msg; a2: uint16_t): cint {.cdecl,
    importc: "nng_msg_header_insert_u16", header: nngHeader.}
proc nng_msg_header_insert_u32*(a1: ptr nng_msg; a2: uint32_t): cint {.cdecl,
    importc: "nng_msg_header_insert_u32", header: nngHeader.}
proc nng_msg_header_insert_u64*(a1: ptr nng_msg; a2: uint64_t): cint {.cdecl,
    importc: "nng_msg_header_insert_u64", header: nngHeader.}
proc nng_msg_header_chop_u16*(a1: ptr nng_msg; a2: ptr uint16_t): cint {.cdecl,
    importc: "nng_msg_header_chop_u16", header: nngHeader.}
proc nng_msg_header_chop_u32*(a1: ptr nng_msg; a2: ptr uint32_t): cint {.cdecl,
    importc: "nng_msg_header_chop_u32", header: nngHeader.}
proc nng_msg_header_chop_u64*(a1: ptr nng_msg; a2: ptr uint64_t): cint {.cdecl,
    importc: "nng_msg_header_chop_u64", header: nngHeader.}
proc nng_msg_header_trim_u16*(a1: ptr nng_msg; a2: ptr uint16_t): cint {.cdecl,
    importc: "nng_msg_header_trim_u16", header: nngHeader.}
proc nng_msg_header_trim_u32*(a1: ptr nng_msg; a2: ptr uint32_t): cint {.cdecl,
    importc: "nng_msg_header_trim_u32", header: nngHeader.}
proc nng_msg_header_trim_u64*(a1: ptr nng_msg; a2: ptr uint64_t): cint {.cdecl,
    importc: "nng_msg_header_trim_u64", header: nngHeader.}
proc nng_msg_append_u16*(a1: ptr nng_msg; a2: uint16_t): cint {.cdecl,
    importc: "nng_msg_append_u16", header: nngHeader.}
proc nng_msg_append_u32*(a1: ptr nng_msg; a2: uint32_t): cint {.cdecl,
    importc: "nng_msg_append_u32", header: nngHeader.}
proc nng_msg_append_u64*(a1: ptr nng_msg; a2: uint64_t): cint {.cdecl,
    importc: "nng_msg_append_u64", header: nngHeader.}
proc nng_msg_insert_u16*(a1: ptr nng_msg; a2: uint16_t): cint {.cdecl,
    importc: "nng_msg_insert_u16", header: nngHeader.}
proc nng_msg_insert_u32*(a1: ptr nng_msg; a2: uint32_t): cint {.cdecl,
    importc: "nng_msg_insert_u32", header: nngHeader.}
proc nng_msg_insert_u64*(a1: ptr nng_msg; a2: uint64_t): cint {.cdecl,
    importc: "nng_msg_insert_u64", header: nngHeader.}
proc nng_msg_chop_u16*(a1: ptr nng_msg; a2: ptr uint16_t): cint {.cdecl,
    importc: "nng_msg_chop_u16", header: nngHeader.}
proc nng_msg_chop_u32*(a1: ptr nng_msg; a2: ptr uint32_t): cint {.cdecl,
    importc: "nng_msg_chop_u32", header: nngHeader.}
proc nng_msg_chop_u64*(a1: ptr nng_msg; a2: ptr uint64_t): cint {.cdecl,
    importc: "nng_msg_chop_u64", header: nngHeader.}
proc nng_msg_trim_u16*(a1: ptr nng_msg; a2: ptr uint16_t): cint {.cdecl,
    importc: "nng_msg_trim_u16", header: nngHeader.}
proc nng_msg_trim_u32*(a1: ptr nng_msg; a2: ptr uint32_t): cint {.cdecl,
    importc: "nng_msg_trim_u32", header: nngHeader.}
proc nng_msg_trim_u64*(a1: ptr nng_msg; a2: ptr uint64_t): cint {.cdecl,
    importc: "nng_msg_trim_u64", header: nngHeader.}
proc nng_msg_dup*(a1: ptr ptr nng_msg; a2: ptr nng_msg): cint {.cdecl,
    importc: "nng_msg_dup", header: nngHeader.}
proc nng_msg_clear*(a1: ptr nng_msg) {.cdecl, importc: "nng_msg_clear",
                                   header: nngHeader.}
proc nng_msg_header_clear*(a1: ptr nng_msg) {.cdecl, importc: "nng_msg_header_clear",
    header: nngHeader.}
proc nng_msg_set_pipe*(a1: ptr nng_msg; a2: nng_pipe) {.cdecl,
    importc: "nng_msg_set_pipe", header: nngHeader.}
proc nng_msg_get_pipe*(a1: ptr nng_msg): nng_pipe {.cdecl,
    importc: "nng_msg_get_pipe", header: nngHeader.}

proc nng_pipe_get*(a1: nng_pipe; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.cdecl,
    importc: "nng_pipe_get", header: nngHeader.}
proc nng_pipe_get_bool*(a1: nng_pipe; a2: cstring; a3: ptr bool): cint {.cdecl,
    importc: "nng_pipe_get_bool", header: nngHeader.}
proc nng_pipe_get_int*(a1: nng_pipe; a2: cstring; a3: ptr cint): cint {.cdecl,
    importc: "nng_pipe_get_int", header: nngHeader.}
proc nng_pipe_get_ms*(a1: nng_pipe; a2: cstring; a3: ptr nng_duration): cint {.cdecl,
    importc: "nng_pipe_get_ms", header: nngHeader.}
proc nng_pipe_get_size*(a1: nng_pipe; a2: cstring; a3: ptr csize_t): cint {.cdecl,
    importc: "nng_pipe_get_size", header: nngHeader.}
proc nng_pipe_get_uint64*(a1: nng_pipe; a2: cstring; a3: ptr uint64_t): cint {.cdecl,
    importc: "nng_pipe_get_uint64", header: nngHeader.}
proc nng_pipe_get_string*(a1: nng_pipe; a2: cstring; a3: cstringArray): cint {.cdecl,
    importc: "nng_pipe_get_string", header: nngHeader.}
proc nng_pipe_get_ptr*(a1: nng_pipe; a2: cstring; a3: ptr pointer): cint {.cdecl,
    importc: "nng_pipe_get_ptr", header: nngHeader.}
proc nng_pipe_get_addr*(a1: nng_pipe; a2: cstring; a3: ptr nng_sockaddr): cint {.cdecl,
    importc: "nng_pipe_get_addr", header: nngHeader.}
proc nng_pipe_close*(a1: nng_pipe): cint {.cdecl, importc: "nng_pipe_close",
                                       header: nngHeader.}
proc nng_pipe_id*(a1: nng_pipe): cint {.cdecl, importc: "nng_pipe_id",
                                    header: nngHeader.}
proc nng_pipe_socket*(a1: nng_pipe): nng_socket {.cdecl, importc: "nng_pipe_socket",
    header: nngHeader.}
proc nng_pipe_dialer*(a1: nng_pipe): nng_dialer {.cdecl, importc: "nng_pipe_dialer",
    header: nngHeader.}
proc nng_pipe_listener*(a1: nng_pipe): nng_listener {.cdecl,
    importc: "nng_pipe_listener", header: nngHeader.}

const
  NNG_FLAG_ALLOC* = 1'u
  NNG_FLAG_NONBLOCK* = 2'u


const
  NNG_OPT_SOCKNAME* = "socket-name"
  NNG_OPT_RAW* = "raw"
  NNG_OPT_PROTO* = "protocol"
  NNG_OPT_PROTONAME* = "protocol-name"
  NNG_OPT_PEER* = "peer"
  NNG_OPT_PEERNAME* = "peer-name"
  NNG_OPT_RECVBUF* = "recv-buffer"
  NNG_OPT_SENDBUF* = "send-buffer"
  NNG_OPT_RECVFD* = "recv-fd"
  NNG_OPT_SENDFD* = "send-fd"
  NNG_OPT_RECVTIMEO* = "recv-timeout"
  NNG_OPT_SENDTIMEO* = "send-timeout"
  NNG_OPT_LOCADDR* = "local-address"
  NNG_OPT_REMADDR* = "remote-address"
  NNG_OPT_URL* = "url"
  NNG_OPT_MAXTTL* = "ttl-max"
  NNG_OPT_RECVMAXSZ* = "recv-size-max"
  NNG_OPT_RECONNMINT* = "reconnect-time-min"
  NNG_OPT_RECONNMAXT* = "reconnect-time-max"


const
  NNG_OPT_TLS_CONFIG* = "tls-config"


const
  NNG_OPT_TLS_AUTH_MODE* = "tls-authmode"


const
  NNG_OPT_TLS_CERT_KEY_FILE* = "tls-cert-key-file"


const
  NNG_OPT_TLS_CA_FILE* = "tls-ca-file"


const
  NNG_OPT_TLS_SERVER_NAME* = "tls-server-name"


const
  NNG_OPT_TLS_VERIFIED* = "tls-verified"


const
  NNG_OPT_TLS_PEER_CN* = "tls-peer-cn"


const
  NNG_OPT_TLS_PEER_ALT_NAMES* = "tls-peer-alt-names"


const
  NNG_OPT_TCP_NODELAY* = "tcp-nodelay"


const
  NNG_OPT_TCP_KEEPALIVE* = "tcp-keepalive"


const
  NNG_OPT_TCP_BOUND_PORT* = "tcp-bound-port"


const
  NNG_OPT_IPC_SECURITY_DESCRIPTOR* = "ipc:security-descriptor"


const
  NNG_OPT_IPC_PERMISSIONS* = "ipc:permissions"


const
  NNG_OPT_PEER_UID* = "ipc:peer-uid"
  NNG_OPT_IPC_PEER_UID* = NNG_OPT_PEER_UID


const
  NNG_OPT_PEER_GID* = "ipc:peer-gid"
  NNG_OPT_IPC_PEER_GID* = NNG_OPT_PEER_GID


const
  NNG_OPT_PEER_PID* = "ipc:peer-pid"
  NNG_OPT_IPC_PEER_PID* = NNG_OPT_PEER_PID


const
  NNG_OPT_PEER_ZONEID* = "ipc:peer-zoneid"
  NNG_OPT_IPC_PEER_ZONEID* = NNG_OPT_PEER_ZONEID


const
  NNG_OPT_WS_REQUEST_HEADERS* = "ws:request-headers"


const
  NNG_OPT_WS_RESPONSE_HEADERS* = "ws:response-headers"


const
  NNG_OPT_WS_RESPONSE_HEADER* = "ws:response-header:"


const
  NNG_OPT_WS_REQUEST_HEADER* = "ws:request-header:"


const
  NNG_OPT_WS_REQUEST_URI* = "ws:request-uri"


const
  NNG_OPT_WS_SENDMAXFRAME* = "ws:txframe-max"


const
  NNG_OPT_WS_RECVMAXFRAME* = "ws:rxframe-max"


const
  NNG_OPT_WS_PROTOCOL* = "ws:protocol"


const
  NNG_OPT_WS_SEND_TEXT* = "ws:send-text"


const
  NNG_OPT_WS_RECV_TEXT* = "ws:recv-text"


const
  NNG_OPT_SOCKET_FD* = "socket:fd"


proc nng_stats_get*(a1: ptr ptr nng_stat): cint {.cdecl, importc: "nng_stats_get",
    header: nngHeader.}

proc nng_stats_free*(a1: ptr nng_stat) {.cdecl, importc: "nng_stats_free",
                                     header: nngHeader.}

proc nng_stats_dump*(a1: ptr nng_stat) {.cdecl, importc: "nng_stats_dump",
                                     header: nngHeader.}

proc nng_stat_next*(a1: ptr nng_stat): ptr nng_stat {.cdecl, importc: "nng_stat_next",
    header: nngHeader.}

proc nng_stat_child*(a1: ptr nng_stat): ptr nng_stat {.cdecl,
    importc: "nng_stat_child", header: nngHeader.}

proc nng_stat_name*(a1: ptr nng_stat): cstring {.cdecl, importc: "nng_stat_name",
    header: nngHeader.}

proc nng_stat_type*(a1: ptr nng_stat): cint {.cdecl, importc: "nng_stat_type",
    header: nngHeader.}

proc nng_stat_find*(a1: ptr nng_stat; a2: cstring): ptr nng_stat {.cdecl,
    importc: "nng_stat_find", header: nngHeader.}

proc nng_stat_find_socket*(a1: ptr nng_stat; a2: nng_socket): ptr nng_stat {.cdecl,
    importc: "nng_stat_find_socket", header: nngHeader.}

proc nng_stat_find_dialer*(a1: ptr nng_stat; a2: nng_dialer): ptr nng_stat {.cdecl,
    importc: "nng_stat_find_dialer", header: nngHeader.}

proc nng_stat_find_listener*(a1: ptr nng_stat; a2: nng_listener): ptr nng_stat {.cdecl,
    importc: "nng_stat_find_listener", header: nngHeader.}
type
  nng_stat_type_enum* {.size: sizeof(cint).} = enum
    NNG_STAT_SCOPE = 0, NNG_STAT_LEVEL = 1, NNG_STAT_COUNTER = 2, NNG_STAT_STRING = 3,
    NNG_STAT_BOOLEAN = 4, NNG_STAT_ID = 5



proc nng_stat_unit*(a1: ptr nng_stat): cint {.cdecl, importc: "nng_stat_unit",
    header: nngHeader.}
type
  nng_unit_enum* {.size: sizeof(cint).} = enum
    NNG_UNIT_NONE = 0, NNG_UNIT_BYTES = 1, NNG_UNIT_MESSAGES = 2, NNG_UNIT_MILLIS = 3,
    NNG_UNIT_EVENTS = 4



proc nng_stat_value*(a1: ptr nng_stat): uint64_t {.cdecl, importc: "nng_stat_value",
    header: nngHeader.}

proc nng_stat_bool*(a1: ptr nng_stat): bool {.cdecl, importc: "nng_stat_bool",
    header: nngHeader.}

proc nng_stat_string*(a1: ptr nng_stat): cstring {.cdecl, importc: "nng_stat_string",
    header: nngHeader.}

proc nng_stat_desc*(a1: ptr nng_stat): cstring {.cdecl, importc: "nng_stat_desc",
    header: nngHeader.}

proc nng_stat_timestamp*(a1: ptr nng_stat): uint64_t {.cdecl,
    importc: "nng_stat_timestamp", header: nngHeader.}

proc nng_device*(a1: nng_socket; a2: nng_socket): cint {.cdecl, importc: "nng_device",
    header: nngHeader.}

proc nng_device_aio*(a1: ptr nng_aio; a2: nng_socket; a3: nng_socket) {.cdecl,
    importc: "nng_device_aio", header: nngHeader.}

type
  nng_errno_enum* {.size: sizeof(cint).} = enum
    NNG_EINTR = 1, NNG_ENOMEM = 2, NNG_EINVAL = 3, NNG_EBUSY = 4, NNG_ETIMEDOUT = 5,
    NNG_ECONNREFUSED = 6, NNG_ECLOSED = 7, NNG_EAGAIN = 8, NNG_ENOTSUP = 9,
    NNG_EADDRINUSE = 10, NNG_ESTATE = 11, NNG_ENOENT = 12, NNG_EPROTO = 13,
    NNG_EUNREACHABLE = 14, NNG_EADDRINVAL = 15, NNG_EPERM = 16, NNG_EMSGSIZE = 17,
    NNG_ECONNABORTED = 18, NNG_ECONNRESET = 19, NNG_ECANCELED = 20, NNG_ENOFILES = 21,
    NNG_ENOSPC = 22, NNG_EEXIST = 23, NNG_EREADONLY = 24, NNG_EWRITEONLY = 25,
    NNG_ECRYPTO = 26, NNG_EPEERAUTH = 27, NNG_ENOARG = 28, NNG_EAMBIGUOUS = 29,
    NNG_EBADTYPE = 30, NNG_ECONNSHUT = 31, NNG_EINTERNAL = 1000,
    NNG_ESYSERR = 0x10000000, NNG_ETRANERR = 0x20000000



type
  nng_url* {.importc: "nng_url", header: nngHeader, bycopy.} = object
    u_rawurl* {.importc: "u_rawurl".}: cstring
    u_scheme* {.importc: "u_scheme".}: cstring
    u_userinfo* {.importc: "u_userinfo".}: cstring
    u_host* {.importc: "u_host".}: cstring
    u_hostname* {.importc: "u_hostname".}: cstring
    u_port* {.importc: "u_port".}: cstring
    u_path* {.importc: "u_path".}: cstring
    u_query* {.importc: "u_query".}: cstring
    u_fragment* {.importc: "u_fragment".}: cstring
    u_requri* {.importc: "u_requri".}: cstring



proc nng_url_parse*(a1: ptr ptr nng_url; a2: cstring): cint {.cdecl,
    importc: "nng_url_parse", header: nngHeader.}

proc nng_url_free*(a1: ptr nng_url) {.cdecl, importc: "nng_url_free", header: nngHeader.}

proc nng_url_clone*(a1: ptr ptr nng_url; a2: ptr nng_url): cint {.cdecl,
    importc: "nng_url_clone", header: nngHeader.}

proc nng_version*(): cstring {.cdecl, importc: "nng_version", header: nngHeader.}


proc nng_stream_free*(a1: ptr nng_stream) {.cdecl, importc: "nng_stream_free",
                                        header: nngHeader.}
proc nng_stream_close*(a1: ptr nng_stream) {.cdecl, importc: "nng_stream_close",
    header: nngHeader.}
proc nng_stream_send*(a1: ptr nng_stream; a2: ptr nng_aio) {.cdecl,
    importc: "nng_stream_send", header: nngHeader.}
proc nng_stream_recv*(a1: ptr nng_stream; a2: ptr nng_aio) {.cdecl,
    importc: "nng_stream_recv", header: nngHeader.}
proc nng_stream_get*(a1: ptr nng_stream; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
    cdecl, importc: "nng_stream_get", header: nngHeader.}
proc nng_stream_get_bool*(a1: ptr nng_stream; a2: cstring; a3: ptr bool): cint {.cdecl,
    importc: "nng_stream_get_bool", header: nngHeader.}
proc nng_stream_get_int*(a1: ptr nng_stream; a2: cstring; a3: ptr cint): cint {.cdecl,
    importc: "nng_stream_get_int", header: nngHeader.}
proc nng_stream_get_ms*(a1: ptr nng_stream; a2: cstring; a3: ptr nng_duration): cint {.
    cdecl, importc: "nng_stream_get_ms", header: nngHeader.}
proc nng_stream_get_size*(a1: ptr nng_stream; a2: cstring; a3: ptr csize_t): cint {.cdecl,
    importc: "nng_stream_get_size", header: nngHeader.}
proc nng_stream_get_uint64*(a1: ptr nng_stream; a2: cstring; a3: ptr uint64_t): cint {.
    cdecl, importc: "nng_stream_get_uint64", header: nngHeader.}
proc nng_stream_get_string*(a1: ptr nng_stream; a2: cstring; a3: cstringArray): cint {.
    cdecl, importc: "nng_stream_get_string", header: nngHeader.}
proc nng_stream_get_ptr*(a1: ptr nng_stream; a2: cstring; a3: ptr pointer): cint {.cdecl,
    importc: "nng_stream_get_ptr", header: nngHeader.}
proc nng_stream_get_addr*(a1: ptr nng_stream; a2: cstring; a3: ptr nng_sockaddr): cint {.
    cdecl, importc: "nng_stream_get_addr", header: nngHeader.}
proc nng_stream_set*(a1: ptr nng_stream; a2: cstring; a3: pointer; a4: csize_t): cint {.
    cdecl, importc: "nng_stream_set", header: nngHeader.}
proc nng_stream_set_bool*(a1: ptr nng_stream; a2: cstring; a3: bool): cint {.cdecl,
    importc: "nng_stream_set_bool", header: nngHeader.}
proc nng_stream_set_int*(a1: ptr nng_stream; a2: cstring; a3: cint): cint {.cdecl,
    importc: "nng_stream_set_int", header: nngHeader.}
proc nng_stream_set_ms*(a1: ptr nng_stream; a2: cstring; a3: nng_duration): cint {.cdecl,
    importc: "nng_stream_set_ms", header: nngHeader.}
proc nng_stream_set_size*(a1: ptr nng_stream; a2: cstring; a3: csize_t): cint {.cdecl,
    importc: "nng_stream_set_size", header: nngHeader.}
proc nng_stream_set_uint64*(a1: ptr nng_stream; a2: cstring; a3: uint64_t): cint {.cdecl,
    importc: "nng_stream_set_uint64", header: nngHeader.}
proc nng_stream_set_string*(a1: ptr nng_stream; a2: cstring; a3: cstring): cint {.cdecl,
    importc: "nng_stream_set_string", header: nngHeader.}
proc nng_stream_set_ptr*(a1: ptr nng_stream; a2: cstring; a3: pointer): cint {.cdecl,
    importc: "nng_stream_set_ptr", header: nngHeader.}
proc nng_stream_dialer_alloc*(a1: ptr ptr nng_stream_dialer; a2: cstring): cint {.cdecl,
    importc: "nng_stream_dialer_alloc", header: nngHeader.}
proc nng_stream_dialer_alloc_url*(a1: ptr ptr nng_stream_dialer; a2: ptr nng_url): cint {.
    cdecl, importc: "nng_stream_dialer_alloc_url", header: nngHeader.}
proc nng_stream_dialer_free*(a1: ptr nng_stream_dialer) {.cdecl,
    importc: "nng_stream_dialer_free", header: nngHeader.}
proc nng_stream_dialer_close*(a1: ptr nng_stream_dialer) {.cdecl,
    importc: "nng_stream_dialer_close", header: nngHeader.}
proc nng_stream_dialer_dial*(a1: ptr nng_stream_dialer; a2: ptr nng_aio) {.cdecl,
    importc: "nng_stream_dialer_dial", header: nngHeader.}
proc nng_stream_dialer_set*(a1: ptr nng_stream_dialer; a2: cstring; a3: pointer;
                           a4: csize_t): cint {.cdecl,
    importc: "nng_stream_dialer_set", header: nngHeader.}
proc nng_stream_dialer_get*(a1: ptr nng_stream_dialer; a2: cstring; a3: pointer;
                           a4: ptr csize_t): cint {.cdecl,
    importc: "nng_stream_dialer_get", header: nngHeader.}
proc nng_stream_dialer_get_bool*(a1: ptr nng_stream_dialer; a2: cstring; a3: ptr bool): cint {.
    cdecl, importc: "nng_stream_dialer_get_bool", header: nngHeader.}
proc nng_stream_dialer_get_int*(a1: ptr nng_stream_dialer; a2: cstring; a3: ptr cint): cint {.
    cdecl, importc: "nng_stream_dialer_get_int", header: nngHeader.}
proc nng_stream_dialer_get_ms*(a1: ptr nng_stream_dialer; a2: cstring;
                              a3: ptr nng_duration): cint {.cdecl,
    importc: "nng_stream_dialer_get_ms", header: nngHeader.}
proc nng_stream_dialer_get_size*(a1: ptr nng_stream_dialer; a2: cstring;
                                a3: ptr csize_t): cint {.cdecl,
    importc: "nng_stream_dialer_get_size", header: nngHeader.}
proc nng_stream_dialer_get_uint64*(a1: ptr nng_stream_dialer; a2: cstring;
                                  a3: ptr uint64_t): cint {.cdecl,
    importc: "nng_stream_dialer_get_uint64", header: nngHeader.}
proc nng_stream_dialer_get_string*(a1: ptr nng_stream_dialer; a2: cstring;
                                  a3: cstringArray): cint {.cdecl,
    importc: "nng_stream_dialer_get_string", header: nngHeader.}
proc nng_stream_dialer_get_ptr*(a1: ptr nng_stream_dialer; a2: cstring;
                               a3: ptr pointer): cint {.cdecl,
    importc: "nng_stream_dialer_get_ptr", header: nngHeader.}
proc nng_stream_dialer_get_addr*(a1: ptr nng_stream_dialer; a2: cstring;
                                a3: ptr nng_sockaddr): cint {.cdecl,
    importc: "nng_stream_dialer_get_addr", header: nngHeader.}
proc nng_stream_dialer_set_bool*(a1: ptr nng_stream_dialer; a2: cstring; a3: bool): cint {.
    cdecl, importc: "nng_stream_dialer_set_bool", header: nngHeader.}
proc nng_stream_dialer_set_int*(a1: ptr nng_stream_dialer; a2: cstring; a3: cint): cint {.
    cdecl, importc: "nng_stream_dialer_set_int", header: nngHeader.}
proc nng_stream_dialer_set_ms*(a1: ptr nng_stream_dialer; a2: cstring;
                              a3: nng_duration): cint {.cdecl,
    importc: "nng_stream_dialer_set_ms", header: nngHeader.}
proc nng_stream_dialer_set_size*(a1: ptr nng_stream_dialer; a2: cstring; a3: csize_t): cint {.
    cdecl, importc: "nng_stream_dialer_set_size", header: nngHeader.}
proc nng_stream_dialer_set_uint64*(a1: ptr nng_stream_dialer; a2: cstring;
                                  a3: uint64_t): cint {.cdecl,
    importc: "nng_stream_dialer_set_uint64", header: nngHeader.}
proc nng_stream_dialer_set_string*(a1: ptr nng_stream_dialer; a2: cstring; a3: cstring): cint {.
    cdecl, importc: "nng_stream_dialer_set_string", header: nngHeader.}
proc nng_stream_dialer_set_ptr*(a1: ptr nng_stream_dialer; a2: cstring; a3: pointer): cint {.
    cdecl, importc: "nng_stream_dialer_set_ptr", header: nngHeader.}
proc nng_stream_dialer_set_addr*(a1: ptr nng_stream_dialer; a2: cstring;
                                a3: ptr nng_sockaddr): cint {.cdecl,
    importc: "nng_stream_dialer_set_addr", header: nngHeader.}
proc nng_stream_listener_alloc*(a1: ptr ptr nng_stream_listener; a2: cstring): cint {.
    cdecl, importc: "nng_stream_listener_alloc", header: nngHeader.}
proc nng_stream_listener_alloc_url*(a1: ptr ptr nng_stream_listener; a2: ptr nng_url): cint {.
    cdecl, importc: "nng_stream_listener_alloc_url", header: nngHeader.}
proc nng_stream_listener_free*(a1: ptr nng_stream_listener) {.cdecl,
    importc: "nng_stream_listener_free", header: nngHeader.}
proc nng_stream_listener_close*(a1: ptr nng_stream_listener) {.cdecl,
    importc: "nng_stream_listener_close", header: nngHeader.}
proc nng_stream_listener_listen*(a1: ptr nng_stream_listener): cint {.cdecl,
    importc: "nng_stream_listener_listen", header: nngHeader.}
proc nng_stream_listener_accept*(a1: ptr nng_stream_listener; a2: ptr nng_aio) {.cdecl,
    importc: "nng_stream_listener_accept", header: nngHeader.}
proc nng_stream_listener_set*(a1: ptr nng_stream_listener; a2: cstring; a3: pointer;
                             a4: csize_t): cint {.cdecl,
    importc: "nng_stream_listener_set", header: nngHeader.}
proc nng_stream_listener_get*(a1: ptr nng_stream_listener; a2: cstring; a3: pointer;
                             a4: ptr csize_t): cint {.cdecl,
    importc: "nng_stream_listener_get", header: nngHeader.}
proc nng_stream_listener_get_bool*(a1: ptr nng_stream_listener; a2: cstring;
                                  a3: ptr bool): cint {.cdecl,
    importc: "nng_stream_listener_get_bool", header: nngHeader.}
proc nng_stream_listener_get_int*(a1: ptr nng_stream_listener; a2: cstring;
                                 a3: ptr cint): cint {.cdecl,
    importc: "nng_stream_listener_get_int", header: nngHeader.}
proc nng_stream_listener_get_ms*(a1: ptr nng_stream_listener; a2: cstring;
                                a3: ptr nng_duration): cint {.cdecl,
    importc: "nng_stream_listener_get_ms", header: nngHeader.}
proc nng_stream_listener_get_size*(a1: ptr nng_stream_listener; a2: cstring;
                                  a3: ptr csize_t): cint {.cdecl,
    importc: "nng_stream_listener_get_size", header: nngHeader.}
proc nng_stream_listener_get_uint64*(a1: ptr nng_stream_listener; a2: cstring;
                                    a3: ptr uint64_t): cint {.cdecl,
    importc: "nng_stream_listener_get_uint64", header: nngHeader.}
proc nng_stream_listener_get_string*(a1: ptr nng_stream_listener; a2: cstring;
                                    a3: cstringArray): cint {.cdecl,
    importc: "nng_stream_listener_get_string", header: nngHeader.}
proc nng_stream_listener_get_ptr*(a1: ptr nng_stream_listener; a2: cstring;
                                 a3: ptr pointer): cint {.cdecl,
    importc: "nng_stream_listener_get_ptr", header: nngHeader.}
proc nng_stream_listener_get_addr*(a1: ptr nng_stream_listener; a2: cstring;
                                  a3: ptr nng_sockaddr): cint {.cdecl,
    importc: "nng_stream_listener_get_addr", header: nngHeader.}
proc nng_stream_listener_set_bool*(a1: ptr nng_stream_listener; a2: cstring; a3: bool): cint {.
    cdecl, importc: "nng_stream_listener_set_bool", header: nngHeader.}
proc nng_stream_listener_set_int*(a1: ptr nng_stream_listener; a2: cstring; a3: cint): cint {.
    cdecl, importc: "nng_stream_listener_set_int", header: nngHeader.}
proc nng_stream_listener_set_ms*(a1: ptr nng_stream_listener; a2: cstring;
                                a3: nng_duration): cint {.cdecl,
    importc: "nng_stream_listener_set_ms", header: nngHeader.}
proc nng_stream_listener_set_size*(a1: ptr nng_stream_listener; a2: cstring;
                                  a3: csize_t): cint {.cdecl,
    importc: "nng_stream_listener_set_size", header: nngHeader.}
proc nng_stream_listener_set_uint64*(a1: ptr nng_stream_listener; a2: cstring;
                                    a3: uint64_t): cint {.cdecl,
    importc: "nng_stream_listener_set_uint64", header: nngHeader.}
proc nng_stream_listener_set_string*(a1: ptr nng_stream_listener; a2: cstring;
                                    a3: cstring): cint {.cdecl,
    importc: "nng_stream_listener_set_string", header: nngHeader.}
proc nng_stream_listener_set_ptr*(a1: ptr nng_stream_listener; a2: cstring;
                                 a3: pointer): cint {.cdecl,
    importc: "nng_stream_listener_set_ptr", header: nngHeader.}
proc nng_stream_listener_set_addr*(a1: ptr nng_stream_listener; a2: cstring;
                                  a3: ptr nng_sockaddr): cint {.cdecl,
    importc: "nng_stream_listener_set_addr", header: nngHeader.}



proc nng_udp_open*(udpp: ptr ptr nng_udp; sa: ptr nng_sockaddr): cint {.cdecl,
    importc: "nng_udp_open", header: nngHeader.}

proc nng_udp_close*(udp: ptr nng_udp) {.cdecl, importc: "nng_udp_close",
                                    header: nngHeader.}

proc nng_udp_sockname*(udp: ptr nng_udp; sa: ptr nng_sockaddr): cint {.cdecl,
    importc: "nng_udp_sockname", header: nngHeader.}

proc nng_udp_send*(udp: ptr nng_udp; aio: ptr nng_aio) {.cdecl, importc: "nng_udp_send",
    header: nngHeader.}

proc nng_udp_recv*(udp: ptr nng_udp; aio: ptr nng_aio) {.cdecl, importc: "nng_udp_recv",
    header: nngHeader.}

proc nng_udp_multicast_membership*(udp: ptr nng_udp; sa: ptr nng_sockaddr; join: bool): cint {.
    cdecl, importc: "nng_udp_multicast_membership", header: nngHeader.}
when not defined(NNG_ELIDE_DEPRECATED):
  proc nng_msg_getopt*(a1: ptr nng_msg; a2: cint; a3: pointer; a4: ptr csize_t): cint {.
      cdecl, importc: "nng_msg_getopt", header: nngHeader.}
  proc nng_getopt*(a1: nng_socket; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
      cdecl, importc: "nng_getopt", header: nngHeader.}
  proc nng_getopt_bool*(a1: nng_socket; a2: cstring; a3: ptr bool): cint {.cdecl,
      importc: "nng_getopt_bool", header: nngHeader.}
  proc nng_getopt_int*(a1: nng_socket; a2: cstring; a3: ptr cint): cint {.cdecl,
      importc: "nng_getopt_int", header: nngHeader.}
  proc nng_getopt_ms*(a1: nng_socket; a2: cstring; a3: ptr nng_duration): cint {.cdecl,
      importc: "nng_getopt_ms", header: nngHeader.}
  proc nng_getopt_size*(a1: nng_socket; a2: cstring; a3: ptr csize_t): cint {.cdecl,
      importc: "nng_getopt_size", header: nngHeader.}
  proc nng_getopt_uint64*(a1: nng_socket; a2: cstring; a3: ptr uint64_t): cint {.cdecl,
      importc: "nng_getopt_uint64", header: nngHeader.}
  proc nng_getopt_ptr*(a1: nng_socket; a2: cstring; a3: ptr pointer): cint {.cdecl,
      importc: "nng_getopt_ptr", header: nngHeader.}
  proc nng_getopt_string*(a1: nng_socket; a2: cstring; a3: cstringArray): cint {.cdecl,
      importc: "nng_getopt_string", header: nngHeader.}
  proc nng_setopt*(a1: nng_socket; a2: cstring; a3: pointer; a4: csize_t): cint {.cdecl,
      importc: "nng_setopt", header: nngHeader.}
  proc nng_setopt_bool*(a1: nng_socket; a2: cstring; a3: bool): cint {.cdecl,
      importc: "nng_setopt_bool", header: nngHeader.}
  proc nng_setopt_int*(a1: nng_socket; a2: cstring; a3: cint): cint {.cdecl,
      importc: "nng_setopt_int", header: nngHeader.}
  proc nng_setopt_ms*(a1: nng_socket; a2: cstring; a3: nng_duration): cint {.cdecl,
      importc: "nng_setopt_ms", header: nngHeader.}
  proc nng_setopt_size*(a1: nng_socket; a2: cstring; a3: csize_t): cint {.cdecl,
      importc: "nng_setopt_size", header: nngHeader.}
  proc nng_setopt_uint64*(a1: nng_socket; a2: cstring; a3: uint64_t): cint {.cdecl,
      importc: "nng_setopt_uint64", header: nngHeader.}
  proc nng_setopt_string*(a1: nng_socket; a2: cstring; a3: cstring): cint {.cdecl,
      importc: "nng_setopt_string", header: nngHeader.}
  proc nng_setopt_ptr*(a1: nng_socket; a2: cstring; a3: pointer): cint {.cdecl,
      importc: "nng_setopt_ptr", header: nngHeader.}
  proc nng_ctx_getopt*(a1: nng_ctx; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
      cdecl, importc: "nng_ctx_getopt", header: nngHeader.}
  proc nng_ctx_getopt_bool*(a1: nng_ctx; a2: cstring; a3: ptr bool): cint {.cdecl,
      importc: "nng_ctx_getopt_bool", header: nngHeader.}
  proc nng_ctx_getopt_int*(a1: nng_ctx; a2: cstring; a3: ptr cint): cint {.cdecl,
      importc: "nng_ctx_getopt_int", header: nngHeader.}
  proc nng_ctx_getopt_ms*(a1: nng_ctx; a2: cstring; a3: ptr nng_duration): cint {.cdecl,
      importc: "nng_ctx_getopt_ms", header: nngHeader.}
  proc nng_ctx_getopt_size*(a1: nng_ctx; a2: cstring; a3: ptr csize_t): cint {.cdecl,
      importc: "nng_ctx_getopt_size", header: nngHeader.}
  proc nng_ctx_setopt*(a1: nng_ctx; a2: cstring; a3: pointer; a4: csize_t): cint {.cdecl,
      importc: "nng_ctx_setopt", header: nngHeader.}
  proc nng_ctx_setopt_bool*(a1: nng_ctx; a2: cstring; a3: bool): cint {.cdecl,
      importc: "nng_ctx_setopt_bool", header: nngHeader.}
  proc nng_ctx_setopt_int*(a1: nng_ctx; a2: cstring; a3: cint): cint {.cdecl,
      importc: "nng_ctx_setopt_int", header: nngHeader.}
  proc nng_ctx_setopt_ms*(a1: nng_ctx; a2: cstring; a3: nng_duration): cint {.cdecl,
      importc: "nng_ctx_setopt_ms", header: nngHeader.}
  proc nng_ctx_setopt_size*(a1: nng_ctx; a2: cstring; a3: csize_t): cint {.cdecl,
      importc: "nng_ctx_setopt_size", header: nngHeader.}
  proc nng_dialer_getopt*(a1: nng_dialer; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
      cdecl, importc: "nng_dialer_getopt", header: nngHeader.}
  proc nng_dialer_getopt_bool*(a1: nng_dialer; a2: cstring; a3: ptr bool): cint {.cdecl,
      importc: "nng_dialer_getopt_bool", header: nngHeader.}
  proc nng_dialer_getopt_int*(a1: nng_dialer; a2: cstring; a3: ptr cint): cint {.cdecl,
      importc: "nng_dialer_getopt_int", header: nngHeader.}
  proc nng_dialer_getopt_ms*(a1: nng_dialer; a2: cstring; a3: ptr nng_duration): cint {.
      cdecl, importc: "nng_dialer_getopt_ms", header: nngHeader.}
  proc nng_dialer_getopt_size*(a1: nng_dialer; a2: cstring; a3: ptr csize_t): cint {.
      cdecl, importc: "nng_dialer_getopt_size", header: nngHeader.}
  proc nng_dialer_getopt_sockaddr*(a1: nng_dialer; a2: cstring; a3: ptr nng_sockaddr): cint {.
      cdecl, importc: "nng_dialer_getopt_sockaddr", header: nngHeader.}
  proc nng_dialer_getopt_uint64*(a1: nng_dialer; a2: cstring; a3: ptr uint64_t): cint {.
      cdecl, importc: "nng_dialer_getopt_uint64", header: nngHeader.}
  proc nng_dialer_getopt_ptr*(a1: nng_dialer; a2: cstring; a3: ptr pointer): cint {.
      cdecl, importc: "nng_dialer_getopt_ptr", header: nngHeader.}
  proc nng_dialer_getopt_string*(a1: nng_dialer; a2: cstring; a3: cstringArray): cint {.
      cdecl, importc: "nng_dialer_getopt_string", header: nngHeader.}
  proc nng_dialer_setopt*(a1: nng_dialer; a2: cstring; a3: pointer; a4: csize_t): cint {.
      cdecl, importc: "nng_dialer_setopt", header: nngHeader.}
  proc nng_dialer_setopt_bool*(a1: nng_dialer; a2: cstring; a3: bool): cint {.cdecl,
      importc: "nng_dialer_setopt_bool", header: nngHeader.}
  proc nng_dialer_setopt_int*(a1: nng_dialer; a2: cstring; a3: cint): cint {.cdecl,
      importc: "nng_dialer_setopt_int", header: nngHeader.}
  proc nng_dialer_setopt_ms*(a1: nng_dialer; a2: cstring; a3: nng_duration): cint {.
      cdecl, importc: "nng_dialer_setopt_ms", header: nngHeader.}
  proc nng_dialer_setopt_size*(a1: nng_dialer; a2: cstring; a3: csize_t): cint {.cdecl,
      importc: "nng_dialer_setopt_size", header: nngHeader.}
  proc nng_dialer_setopt_uint64*(a1: nng_dialer; a2: cstring; a3: uint64_t): cint {.
      cdecl, importc: "nng_dialer_setopt_uint64", header: nngHeader.}
  proc nng_dialer_setopt_ptr*(a1: nng_dialer; a2: cstring; a3: pointer): cint {.cdecl,
      importc: "nng_dialer_setopt_ptr", header: nngHeader.}
  proc nng_dialer_setopt_string*(a1: nng_dialer; a2: cstring; a3: cstring): cint {.
      cdecl, importc: "nng_dialer_setopt_string", header: nngHeader.}
  proc nng_listener_getopt*(a1: nng_listener; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
      cdecl, importc: "nng_listener_getopt", header: nngHeader.}
  proc nng_listener_getopt_bool*(a1: nng_listener; a2: cstring; a3: ptr bool): cint {.
      cdecl, importc: "nng_listener_getopt_bool", header: nngHeader.}
  proc nng_listener_getopt_int*(a1: nng_listener; a2: cstring; a3: ptr cint): cint {.
      cdecl, importc: "nng_listener_getopt_int", header: nngHeader.}
  proc nng_listener_getopt_ms*(a1: nng_listener; a2: cstring; a3: ptr nng_duration): cint {.
      cdecl, importc: "nng_listener_getopt_ms", header: nngHeader.}
  proc nng_listener_getopt_size*(a1: nng_listener; a2: cstring; a3: ptr csize_t): cint {.
      cdecl, importc: "nng_listener_getopt_size", header: nngHeader.}
  proc nng_listener_getopt_sockaddr*(a1: nng_listener; a2: cstring;
                                    a3: ptr nng_sockaddr): cint {.cdecl,
      importc: "nng_listener_getopt_sockaddr", header: nngHeader.}
  proc nng_listener_getopt_uint64*(a1: nng_listener; a2: cstring; a3: ptr uint64_t): cint {.
      cdecl, importc: "nng_listener_getopt_uint64", header: nngHeader.}
  proc nng_listener_getopt_ptr*(a1: nng_listener; a2: cstring; a3: ptr pointer): cint {.
      cdecl, importc: "nng_listener_getopt_ptr", header: nngHeader.}
  proc nng_listener_getopt_string*(a1: nng_listener; a2: cstring; a3: cstringArray): cint {.
      cdecl, importc: "nng_listener_getopt_string", header: nngHeader.}
  proc nng_listener_setopt*(a1: nng_listener; a2: cstring; a3: pointer; a4: csize_t): cint {.
      cdecl, importc: "nng_listener_setopt", header: nngHeader.}
  proc nng_listener_setopt_bool*(a1: nng_listener; a2: cstring; a3: bool): cint {.cdecl,
      importc: "nng_listener_setopt_bool", header: nngHeader.}
  proc nng_listener_setopt_int*(a1: nng_listener; a2: cstring; a3: cint): cint {.cdecl,
      importc: "nng_listener_setopt_int", header: nngHeader.}
  proc nng_listener_setopt_ms*(a1: nng_listener; a2: cstring; a3: nng_duration): cint {.
      cdecl, importc: "nng_listener_setopt_ms", header: nngHeader.}
  proc nng_listener_setopt_size*(a1: nng_listener; a2: cstring; a3: csize_t): cint {.
      cdecl, importc: "nng_listener_setopt_size", header: nngHeader.}
  proc nng_listener_setopt_uint64*(a1: nng_listener; a2: cstring; a3: uint64_t): cint {.
      cdecl, importc: "nng_listener_setopt_uint64", header: nngHeader.}
  proc nng_listener_setopt_ptr*(a1: nng_listener; a2: cstring; a3: pointer): cint {.
      cdecl, importc: "nng_listener_setopt_ptr", header: nngHeader.}
  proc nng_listener_setopt_string*(a1: nng_listener; a2: cstring; a3: cstring): cint {.
      cdecl, importc: "nng_listener_setopt_string", header: nngHeader.}
  proc nng_pipe_getopt*(a1: nng_pipe; a2: cstring; a3: pointer; a4: ptr csize_t): cint {.
      cdecl, importc: "nng_pipe_getopt", header: nngHeader.}
  proc nng_pipe_getopt_bool*(a1: nng_pipe; a2: cstring; a3: ptr bool): cint {.cdecl,
      importc: "nng_pipe_getopt_bool", header: nngHeader.}
  proc nng_pipe_getopt_int*(a1: nng_pipe; a2: cstring; a3: ptr cint): cint {.cdecl,
      importc: "nng_pipe_getopt_int", header: nngHeader.}
  proc nng_pipe_getopt_ms*(a1: nng_pipe; a2: cstring; a3: ptr nng_duration): cint {.
      cdecl, importc: "nng_pipe_getopt_ms", header: nngHeader.}
  proc nng_pipe_getopt_size*(a1: nng_pipe; a2: cstring; a3: ptr csize_t): cint {.cdecl,
      importc: "nng_pipe_getopt_size", header: nngHeader.}
  proc nng_pipe_getopt_sockaddr*(a1: nng_pipe; a2: cstring; a3: ptr nng_sockaddr): cint {.
      cdecl, importc: "nng_pipe_getopt_sockaddr", header: nngHeader.}
  proc nng_pipe_getopt_uint64*(a1: nng_pipe; a2: cstring; a3: ptr uint64_t): cint {.
      cdecl, importc: "nng_pipe_getopt_uint64", header: nngHeader.}
  proc nng_pipe_getopt_ptr*(a1: nng_pipe; a2: cstring; a3: ptr pointer): cint {.cdecl,
      importc: "nng_pipe_getopt_ptr", header: nngHeader.}
  proc nng_pipe_getopt_string*(a1: nng_pipe; a2: cstring; a3: cstringArray): cint {.
      cdecl, importc: "nng_pipe_getopt_string", header: nngHeader.}
  proc nng_closeall*() {.cdecl, importc: "nng_closeall", header: nngHeader.}
  proc nng_stream_set_addr*(a1: ptr nng_stream; a2: cstring; a3: ptr nng_sockaddr): cint {.
      cdecl, importc: "nng_stream_set_addr", header: nngHeader.}
  proc nng_ctx_get_addr*(a1: nng_ctx; a2: cstring; a3: ptr nng_sockaddr): cint {.cdecl,
      importc: "nng_ctx_get_addr", header: nngHeader.}
  proc nng_ctx_set_addr*(a1: nng_ctx; a2: cstring; a3: ptr nng_sockaddr): cint {.cdecl,
      importc: "nng_ctx_set_addr", header: nngHeader.}

type
  nng_init_parameter* = cint

proc nng_init_set_parameter*(a1: nng_init_parameter; a2: uint64_t) {.cdecl,
    importc: "nng_init_set_parameter", header: nngHeader.}

const
  NNG_INIT_PARAMETER_NONE* = 0
  NNG_INIT_NUM_TASK_THREADS* = 1
  NNG_INIT_NUM_EXPIRE_THREADS* = 2
  NNG_INIT_NUM_POLLER_THREADS* = 3
  NNG_INIT_NUM_RESOLVER_THREADS* = 4
  NNG_INIT_MAX_TASK_THREADS* = 5
  NNG_INIT_MAX_EXPIRE_THREADS* = 6
  NNG_INIT_MAX_POLLER_THREADS* = 7


type
  nng_log_level* {.size: sizeof(cint).} = enum
    NNG_LOG_NONE = 0, NNG_LOG_ERR = 3, NNG_LOG_WARN = 4, NNG_LOG_NOTICE = 5,
    NNG_LOG_INFO = 6, NNG_LOG_DEBUG = 7



type
  nng_log_facility* {.size: sizeof(cint).} = enum
    NNG_LOG_USER = 1, NNG_LOG_DAEMON = 3, NNG_LOG_AUTH = 10, NNG_LOG_LOCAL0 = 16,
    NNG_LOG_LOCAL1 = 17, NNG_LOG_LOCAL2 = 18, NNG_LOG_LOCAL3 = 19, NNG_LOG_LOCAL4 = 20,
    NNG_LOG_LOCAL5 = 21, NNG_LOG_LOCAL6 = 22, NNG_LOG_LOCAL7 = 23



type
  nng_logger* = proc (level: nng_log_level; facility: nng_log_facility; msgid: cstring;
                   msg: cstring) {.cdecl.}


proc nng_null_logger*(a1: nng_log_level; a2: nng_log_facility; a3: cstring; a4: cstring) {.
    cdecl, importc: "nng_null_logger", header: nngHeader.}

proc nng_stderr_logger*(a1: nng_log_level; a2: nng_log_facility; a3: cstring;
                       a4: cstring) {.cdecl, importc: "nng_stderr_logger",
                                    header: nngHeader.}

proc nng_system_logger*(a1: nng_log_level; a2: nng_log_facility; a3: cstring;
                       a4: cstring) {.cdecl, importc: "nng_system_logger",
                                    header: nngHeader.}

proc nng_log_set_facility*(facility: nng_log_facility) {.cdecl,
    importc: "nng_log_set_facility", header: nngHeader.}

proc nng_log_set_level*(level: nng_log_level) {.cdecl, importc: "nng_log_set_level",
    header: nngHeader.}

proc nng_log_get_level*(): nng_log_level {.cdecl, importc: "nng_log_get_level",
                                        header: nngHeader.}

proc nng_log_set_logger*(logger: nng_logger) {.cdecl, importc: "nng_log_set_logger",
    header: nngHeader.}

proc nng_log_err*(msgid: cstring; msg: cstring) {.varargs, cdecl,
    importc: "nng_log_err", header: nngHeader.}
proc nng_log_warn*(msgid: cstring; msg: cstring) {.varargs, cdecl,
    importc: "nng_log_warn", header: nngHeader.}
proc nng_log_notice*(msgid: cstring; msg: cstring) {.varargs, cdecl,
    importc: "nng_log_notice", header: nngHeader.}
proc nng_log_info*(msgid: cstring; msg: cstring) {.varargs, cdecl,
    importc: "nng_log_info", header: nngHeader.}
proc nng_log_debug*(msgid: cstring; msg: cstring) {.varargs, cdecl,
    importc: "nng_log_debug", header: nngHeader.}

proc nng_log_auth*(level: nng_log_level; msgid: cstring; msg: cstring) {.varargs, cdecl,
    importc: "nng_log_auth", header: nngHeader.}

proc nng_clock*(): nng_time {.cdecl, importc: "nng_clock", header: nngHeader.}

proc nng_msleep*(a1: nng_duration) {.cdecl, importc: "nng_msleep", header: nngHeader.}

proc nng_random*(): uint32_t {.cdecl, importc: "nng_random", header: nngHeader.}

proc nng_socket_pair*(a1: array[2, cint]): cint {.cdecl, importc: "nng_socket_pair",
    header: nngHeader.}



proc nng_thread_create*(a1: ptr ptr nng_thread; a2: proc (a1: pointer) {.cdecl.};
                       a3: pointer): cint {.cdecl, importc: "nng_thread_create",
    header: nngHeader.}

proc nng_thread_set_name*(a1: ptr nng_thread; a2: cstring) {.cdecl,
    importc: "nng_thread_set_name", header: nngHeader.}

proc nng_thread_destroy*(a1: ptr nng_thread) {.cdecl, importc: "nng_thread_destroy",
    header: nngHeader.}



proc nng_mtx_alloc*(a1: ptr ptr nng_mtx): cint {.cdecl, importc: "nng_mtx_alloc",
    header: nngHeader.}

proc nng_mtx_free*(a1: ptr nng_mtx) {.cdecl, importc: "nng_mtx_free", header: nngHeader.}

proc nng_mtx_lock*(a1: ptr nng_mtx) {.cdecl, importc: "nng_mtx_lock", header: nngHeader.}

proc nng_mtx_unlock*(a1: ptr nng_mtx) {.cdecl, importc: "nng_mtx_unlock",
                                    header: nngHeader.}


proc nng_cv_alloc*(a1: ptr ptr nng_cv; a2: ptr nng_mtx): cint {.cdecl,
    importc: "nng_cv_alloc", header: nngHeader.}

proc nng_cv_free*(a1: ptr nng_cv) {.cdecl, importc: "nng_cv_free", header: nngHeader.}

proc nng_cv_wait*(a1: ptr nng_cv) {.cdecl, importc: "nng_cv_wait", header: nngHeader.}

proc nng_cv_until*(a1: ptr nng_cv; a2: nng_time): cint {.cdecl, importc: "nng_cv_until",
    header: nngHeader.}

proc nng_cv_wake*(a1: ptr nng_cv) {.cdecl, importc: "nng_cv_wake", header: nngHeader.}

proc nng_cv_wake1*(a1: ptr nng_cv) {.cdecl, importc: "nng_cv_wake1", header: nngHeader.}

proc nng_dialer_get_url*(a1: nng_dialer; a2: ptr ptr nng_url): cint {.cdecl,
    importc: "nng_dialer_get_url", header: nngHeader.}
proc nng_listener_get_url*(a1: nng_listener; a2: ptr ptr nng_url): cint {.cdecl,
    importc: "nng_listener_get_url", header: nngHeader.}