# Generated by tools/nng/gen.sh (c2nim) from nng/protocol/pipeline0/pull.h. Do not edit.
const nngHeader = "nng/protocol/pipeline0/pull.h"
import core

proc nng_pull0_open*(a1: ptr nng_socket): cint {.cdecl, importc: "nng_pull0_open",
    header: nngHeader.}
proc nng_pull0_open_raw*(a1: ptr nng_socket): cint {.cdecl,
    importc: "nng_pull0_open_raw", header: nngHeader.}
when not defined(nng_pull_open):
  const
    nng_pull_open* = nng_pull0_open
when not defined(nng_pull_open_raw):
  const
    nng_pull_open_raw* = nng_pull0_open_raw