# Generated by tools/nng/gen.sh (c2nim) from nng/protocol/reqrep0/rep.h. Do not edit.
const nngHeader = "nng/protocol/reqrep0/rep.h"
import core

proc nng_rep0_open*(a1: ptr nng_socket): cint {.cdecl, importc: "nng_rep0_open",
    header: nngHeader.}
proc nng_rep0_open_raw*(a1: ptr nng_socket): cint {.cdecl,
    importc: "nng_rep0_open_raw", header: nngHeader.}
when not defined(nng_rep_open):
  const
    nng_rep_open* = nng_rep0_open
when not defined(nng_rep_open_raw):
  const
    nng_rep_open_raw* = nng_rep0_open_raw
const
  NNG_REP0_SELF* = 0x31
  NNG_REP0_PEER* = 0x30
  NNG_REP0_SELF_NAME* = "rep"
  NNG_REP0_PEER_NAME* = "req"
