# Generated by tools/nng/gen.sh (c2nim) from nng/protocol/pipeline0/push.h. Do not edit.
const nngHeader = "nng/protocol/pipeline0/push.h"
import core

proc nng_push0_open*(a1: ptr nng_socket): cint {.cdecl, importc: "nng_push0_open",
    header: nngHeader.}
proc nng_push0_open_raw*(a1: ptr nng_socket): cint {.cdecl,
    importc: "nng_push0_open_raw", header: nngHeader.}
when not defined(nng_push_open):
  const
    nng_push_open* = nng_push0_open
when not defined(nng_push_open_raw):
  const
    nng_push_open_raw* = nng_push0_open_raw