# Generated by tools/nng/gen.sh (c2nim) from nng/protocol/reqrep0/req.h. Do not edit.
const nngHeader = "nng/protocol/reqrep0/req.h"
import core

proc nng_req0_open*(a1: ptr nng_socket): cint {.cdecl, importc: "nng_req0_open",
    header: nngHeader.}
proc nng_req0_open_raw*(a1: ptr nng_socket): cint {.cdecl,
    importc: "nng_req0_open_raw", header: nngHeader.}
when not defined(nng_req_open):
  const
    nng_req_open* = nng_req0_open
when not defined(nng_req_open_raw):
  const
    nng_req_open_raw* = nng_req0_open_raw
const
  NNG_REQ0_SELF* = 0x30
  NNG_REQ0_PEER* = 0x31
  NNG_REQ0_SELF_NAME* = "req"
  NNG_REQ0_PEER_NAME* = "rep"
  NNG_OPT_REQ_RESENDTIME* = "req:resend-time"
  NNG_OPT_REQ_RESENDTICK* = "req:resend-tick"
