# Generated by tools/nng/gen.sh (c2nim) from nng/supplemental/tls/tls.h. Do not edit.
const nngHeader = "nng/supplemental/tls/tls.h"
import core
type nng_tls_config* {.importc: "nng_tls_config", header: nngHeader, incompleteStruct.} = object


type
  nng_tls_mode* {.size: sizeof(cint).} = enum
    NNG_TLS_MODE_CLIENT = 0, NNG_TLS_MODE_SERVER = 1
  nng_tls_auth_mode* {.size: sizeof(cint).} = enum
    NNG_TLS_AUTH_MODE_NONE = 0, NNG_TLS_AUTH_MODE_OPTIONAL = 1,
    NNG_TLS_AUTH_MODE_REQUIRED = 2




type
  nng_tls_version* {.size: sizeof(cint).} = enum
    NNG_TLS_1_0 = 0x301, NNG_TLS_1_1 = 0x302, NNG_TLS_1_2 = 0x303, NNG_TLS_1_3 = 0x304



proc nng_tls_config_alloc*(a1: ptr ptr nng_tls_config; a2: nng_tls_mode): cint {.cdecl,
    importc: "nng_tls_config_alloc", header: nngHeader.}

proc nng_tls_config_hold*(a1: ptr nng_tls_config) {.cdecl,
    importc: "nng_tls_config_hold", header: nngHeader.}

proc nng_tls_config_free*(a1: ptr nng_tls_config) {.cdecl,
    importc: "nng_tls_config_free", header: nngHeader.}

proc nng_tls_config_server_name*(a1: ptr nng_tls_config; a2: cstring): cint {.cdecl,
    importc: "nng_tls_config_server_name", header: nngHeader.}

proc nng_tls_config_ca_chain*(a1: ptr nng_tls_config; a2: cstring; a3: cstring): cint {.
    cdecl, importc: "nng_tls_config_ca_chain", header: nngHeader.}

proc nng_tls_config_own_cert*(a1: ptr nng_tls_config; a2: cstring; a3: cstring;
                             a4: cstring): cint {.cdecl,
    importc: "nng_tls_config_own_cert", header: nngHeader.}

proc nng_tls_config_key*(a1: ptr nng_tls_config; a2: ptr uint8_t; a3: csize_t): cint {.
    cdecl, importc: "nng_tls_config_key", header: nngHeader.}

proc nng_tls_config_pass*(a1: ptr nng_tls_config; a2: cstring): cint {.cdecl,
    importc: "nng_tls_config_pass", header: nngHeader.}

proc nng_tls_config_auth_mode*(a1: ptr nng_tls_config; a2: nng_tls_auth_mode): cint {.
    cdecl, importc: "nng_tls_config_auth_mode", header: nngHeader.}

proc nng_tls_config_ca_file*(a1: ptr nng_tls_config; a2: cstring): cint {.cdecl,
    importc: "nng_tls_config_ca_file", header: nngHeader.}

proc nng_tls_config_cert_key_file*(a1: ptr nng_tls_config; a2: cstring; a3: cstring): cint {.
    cdecl, importc: "nng_tls_config_cert_key_file", header: nngHeader.}

proc nng_tls_config_psk*(a1: ptr nng_tls_config; a2: cstring; a3: ptr uint8_t;
                        a4: csize_t): cint {.cdecl, importc: "nng_tls_config_psk",
    header: nngHeader.}

proc nng_tls_config_version*(a1: ptr nng_tls_config; a2: nng_tls_version;
                            a3: nng_tls_version): cint {.cdecl,
    importc: "nng_tls_config_version", header: nngHeader.}

proc nng_tls_engine_name*(): cstring {.cdecl, importc: "nng_tls_engine_name",
                                    header: nngHeader.}

proc nng_tls_engine_description*(): cstring {.cdecl,
    importc: "nng_tls_engine_description", header: nngHeader.}

proc nng_tls_engine_fips_mode*(): bool {.cdecl, importc: "nng_tls_engine_fips_mode",
                                      header: nngHeader.}