#!/usr/bin/env python3
"""Reference wire vectors for proto v0 from Google's implementation on code generated by protoc from the real .proto files.
Usage: /tmp/gvenv/bin/python tools/proto/gen_vectors.py  (needs grpcio-tools); writes tests/vectors/proto_v0.json"""
import json, os, subprocess, sys, tempfile
root = os.path.join(os.path.dirname(__file__), "..", "..")
out = tempfile.mkdtemp()
files = [os.path.join("cicd/internal/v1", f) for f in os.listdir(os.path.join(root, "proto/cicd/internal/v1")) if f.endswith(".proto")]
files.append("cicd/plugin/v1/plugin.proto")
subprocess.check_call([sys.executable, "-m", "grpc_tools.protoc", "-I", os.path.join(root, "proto"), "--python_out=" + out] + files)
sys.path.insert(0, out)
from cicd.internal.v1 import common_pb2, controller_pb2, logs_pb2, step_pb2, executor_pb2, directory_pb2
from cicd.plugin.v1 import plugin_pb2
from google.protobuf import timestamp_pb2, struct_pb2

def ts(s, n): t = timestamp_pb2.Timestamp(); t.seconds = s; t.nanos = n; return t
def hexof(m): return m.SerializeToString(deterministic=True).hex()
V = {}
step = common_pb2.StepRef(run_id="sh1_0192f0a4", seq=7, attempt=2)
r = step_pb2.StepReport(header=common_pb2.Header(protocol=1, request_id="req-1"), step=step, job_token="tok", exit_code=-1,
                        reason="env_rejected", outputs_digest=bytes(range(32)))
r.outputs["VERSION"] = "1.2"; r.outputs["A"] = "b"
V["step_report"] = hexof(r)
b = logs_pb2.LogBatch(header=common_pb2.Header(protocol=1, sent_at=ts(1789980000, 123456789)), step=step, job_token="t")
b.chunks.add(seq=1, stream=logs_pb2.LOG_STREAM_STDOUT, time=ts(1789980001, 5), data=b"hello\n", crc32c=0xDEADBEEF)
b.chunks.add(seq=2, stream=logs_pb2.LOG_STREAM_STDERR, time=ts(1789980002, 0), data=bytes([0, 255, 10]), crc32c=1)
V["log_batch"] = hexof(b)
p = controller_pb2.PollResponse(header=common_pb2.Header(protocol=1), poll_after_ms=500, gate=controller_pb2.GateState(open=True))
c1 = p.commands.add(seq=1); c1.start.step.CopyFrom(step); c1.start.image = "busybox:1.36"; c1.start.command.extend(["sh", "-c", "true"])
c1.start.env["B"] = "2"; c1.start.env["A"] = "1"; c1.start.secret_handles.append("vault:db"); c1.start.timeout_seconds = 3600
c2 = p.commands.add(seq=2); c2.cancel.step.CopyFrom(step); c2.cancel.grace_seconds = 30
c3 = p.commands.add(seq=3); c3.gate.open = False; c3.gate.reason = "logs_unavailable"
V["poll_response"] = hexof(p)
V["journal_entry"] = hexof(executor_pb2.JournalEntry(seq=18446744073709551615, kind="sh", payload=b'{"cmd":"make"}', result=b'{"code":0}', hash=bytes(range(32))))
cs = directory_pb2.ClusterState(header=common_pb2.Header(protocol=1), launch_gate_open=False, gate_reason="no master")
cs.nodes.add(node_id="z1", address="10.0.0.1:4080", role=directory_pb2.NODE_ROLE_MASTER, health=directory_pb2.NODE_HEALTH_UP, lag=42)
cs.nodes.add(node_id="z2", address="10.0.0.2:4080", role=directory_pb2.NODE_ROLE_REPLICA, health=directory_pb2.NODE_HEALTH_RESTORING, lag=0)
V["cluster_state"] = hexof(cs)
e = plugin_pb2.ExecuteStep(protocol=1, step_id="s1", workspace="/cicd/workspace")
e.inputs.update({"a": 1.5, "b": "x", "c": [True, None], "d": {"e": 2}})
e.secret_handles["token"] = "vault:t"
V["execute_step"] = hexof(e)
# forward compatibility: a newer sender adds field 99 (varint) and 100 (bytes) to StepReport
V["step_report_future"] = (r.SerializeToString(deterministic=True) + bytes([0x98, 0x06, 0x05]) + bytes([0xA2, 0x06, 0x02]) + b"zz").hex()
json.dump(V, open(os.path.join(root, "tests/vectors/proto_v0.json"), "w"), indent=1, sort_keys=True)
print(len(V), "vectors")
