## Kubernetes client bindings: modules generated by tools/k8s/gen.sh (c2nim) plus linker flags.
## Build with -d:k8sPrefix=<dir with include/ and lib/ from tools/k8s/build_client.sh>.
import k8sc/[list, keyvalue, apiclient, generic, kubeconfig, incluster, watchutil]
export list, keyvalue, apiclient, generic, kubeconfig, incluster, watchutil

const k8sPrefix* {.strdefine.} = ""
when k8sPrefix.len > 0:
  {.passC: "-I" & k8sPrefix & "/include".}
  {.passL: "-L" & k8sPrefix & "/lib -lkubernetes -Wl,-rpath," & k8sPrefix & "/lib".}

# Connection reuse: the C client creates a libcurl easy handle per call, so every call pays a TLS handshake (~200 ms).
# A curl share handle with a shared connection cache, installed through the client's own curl_pre_invoke_func hook, makes the
# connections survive (measured in ADR 0013: cycle 1.4 s -> 0.5 s, RSS flat). One apiClient (and one share handle) per thread.
proc curl_share_init(): pointer {.importc, header: "<curl/curl.h>".}
proc curl_share_setopt(s: pointer; opt: cint; v: cint): cint {.importc, header: "<curl/curl.h>", discardable.}
proc curl_easy_setopt(h: pointer; opt: cint; v: pointer): cint {.importc, header: "<curl/curl.h>", discardable.}

var connectionShare {.threadvar.}: pointer

proc shareConnections(h: ptr CURL) {.cdecl.} =
  discard curl_easy_setopt(cast[pointer](h), 10100.cint, connectionShare)     # CURLOPT_SHARE

proc enableConnectionCache*(api: ptr apiClient_t) =
  ## call once per apiClient, from the thread that uses it
  connectionShare = curl_share_init()
  discard curl_share_setopt(connectionShare, 1.cint, 5.cint)                  # CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT
  api.curl_pre_invoke_func = shareConnections
