## NNG bindings: modules generated by tools/nng/gen.sh (c2nim) plus linker flags.
## Build with -d:nngPrefix=<dir containing include/ and lib/ of an NNG + mbedTLS install>.
import nngc/[core, tls, proto_req, proto_rep, proto_push, proto_pull]
export core, tls, proto_req, proto_rep, proto_push, proto_pull

const nngPrefix* {.strdefine.} = ""
when nngPrefix.len > 0:
  {.passC: "-I" & nngPrefix & "/include".}
  {.passL: "-L" & nngPrefix & "/lib -lnng -lmbedtls -lmbedx509 -lmbedcrypto -lpthread".}
