apiVersion: v1
kind: Secret
metadata:
  name: cinim-router
  namespace: {{ .Values.sharedNamespace }}
type: Opaque
stringData:
  ROUTER_KEY: {{ required "routerKey is required" .Values.routerKey | quote }}
